// This file is auto-generated by @hey-api/openapi-ts

export const $AddFundToWatchListResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'AddFundToWatchListResponseApiModel',
} as const;

export const $AddReportToDashboardForUserBody = {
  properties: {
    reportIdentifier: {
      type: 'string',
      title: 'Reportidentifier',
    },
    order: {
      type: 'integer',
      title: 'Order',
    },
    selectedFilters: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Selectedfilters',
    },
  },
  type: 'object',
  required: ['reportIdentifier', 'order'],
  title: 'AddReportToDashboardForUserBody',
} as const;

export const $AnonymousApiUser = {
  properties: {},
  type: 'object',
  title: 'AnonymousApiUser',
} as const;

export const $ApiExceptionResponse = {
  properties: {
    code: {
      type: 'integer',
      title: 'Code',
    },
    domain: {
      type: 'integer',
      title: 'Domain',
    },
    message: {
      type: 'string',
      title: 'Message',
    },
  },
  type: 'object',
  required: ['code', 'domain', 'message'],
  title: 'ApiExceptionResponse',
} as const;

export const $AressApiUser = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
      description: 'Unique identifier of user',
    },
    username: {
      type: 'string',
      title: 'Username',
      description: 'Username for the user',
    },
    email: {
      type: 'string',
      title: 'Email',
      description: 'Email for the user.',
    },
    phoneNumber: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Phonenumber',
      description: 'Phone number of the user.',
    },
    nationalCode: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Nationalcode',
      description: 'National code of the user.',
    },
    active: {
      type: 'boolean',
      title: 'Active',
      description:
        'Whether this user is active or not, is always "true" for logged in user.',
    },
    firstName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Firstname',
      description: 'First name of user.',
    },
    lastName: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastname',
      description: 'Last name the user.',
    },
    profilePicture: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Profilepicture',
      description: 'Profile picture url of the user.',
    },
  },
  type: 'object',
  required: [
    'identifier',
    'username',
    'email',
    'phoneNumber',
    'nationalCode',
    'active',
    'firstName',
    'lastName',
    'profilePicture',
  ],
  title: 'AressApiUser',
} as const;

export const $Body_change_profile_picture_users_profile_picture_change_post = {
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['file'],
  title: 'Body_change_profile_picture_users_profile_picture_change_post',
} as const;

export const $Body_login_for_access_token_users_login_post = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: 'string',
          pattern: 'password',
        },
        {
          type: 'null',
        },
      ],
      title: 'Grant Type',
    },
    username: {
      type: 'string',
      title: 'Username',
    },
    password: {
      type: 'string',
      title: 'Password',
    },
    scope: {
      type: 'string',
      title: 'Scope',
      default: '',
    },
    client_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Client Id',
    },
    client_secret: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Client Secret',
    },
  },
  type: 'object',
  required: ['username', 'password'],
  title: 'Body_login_for_access_token_users_login_post',
} as const;

export const $Body_request_new_report_reports_request_post = {
  properties: {
    request_form: {
      $ref: '#/components/schemas/RequestReportForm',
      title: 'Request Form',
    },
    file: {
      anyOf: [
        {
          type: 'string',
          format: 'binary',
        },
        {
          type: 'null',
        },
      ],
      title: 'File',
    },
  },
  type: 'object',
  required: ['request_form'],
  title: 'Body_request_new_report_reports_request_post',
} as const;

export const $Body_save_dashboard_item_screenshot_dashboards__dashboard_id__items__dashboard_item_id__screenshot_post =
  {
    properties: {
      file: {
        type: 'string',
        format: 'binary',
        title: 'File',
      },
      selected_filters: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'null',
          },
        ],
        title: 'Selected Filters',
      },
    },
    type: 'object',
    required: ['file', 'selected_filters'],
    title:
      'Body_save_dashboard_item_screenshot_dashboards__dashboard_id__items__dashboard_item_id__screenshot_post',
  } as const;

export const $Body_save_screenshot_reports__report_id__screenshot_post = {
  properties: {
    selected_filters: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Selected Filters',
    },
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['selected_filters', 'file'],
  title: 'Body_save_screenshot_reports__report_id__screenshot_post',
} as const;

export const $Body_test_user_access_token_users_token_post = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: 'string',
          pattern: 'password',
        },
        {
          type: 'null',
        },
      ],
      title: 'Grant Type',
    },
    username: {
      type: 'string',
      title: 'Username',
    },
    password: {
      type: 'string',
      title: 'Password',
    },
    scope: {
      type: 'string',
      title: 'Scope',
      default: '',
    },
    client_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Client Id',
    },
    client_secret: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Client Secret',
    },
  },
  type: 'object',
  required: ['username', 'password'],
  title: 'Body_test_user_access_token_users_token_post',
} as const;

export const $CaptchaApiModel = {
  properties: {
    value: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Value',
    },
    uid: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Uid',
    },
    required: {
      type: 'boolean',
      title: 'Required',
    },
  },
  type: 'object',
  required: ['value', 'uid', 'required'],
  title: 'CaptchaApiModel',
} as const;

export const $CaptchaType = {
  type: 'string',
  enum: ['image', 'audio'],
  title: 'CaptchaType',
} as const;

export const $ChangeDashboardReportItemSortOrderBody = {
  properties: {
    order: {
      type: 'integer',
      title: 'Order',
    },
  },
  type: 'object',
  required: ['order'],
  title: 'ChangeDashboardReportItemSortOrderBody',
} as const;

export const $ChangeEmailByOtpBody = {
  properties: {
    otp: {
      type: 'string',
      title: 'Otp',
    },
  },
  type: 'object',
  required: ['otp'],
  title: 'ChangeEmailByOtpBody',
} as const;

export const $ChangeEmailByOtpResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'ChangeEmailByOtpResponseApiModel',
} as const;

export const $ChangeEmailGetOtpBody = {
  properties: {
    newEmail: {
      type: 'string',
      title: 'Newemail',
    },
    passwordVerificationToken: {
      type: 'string',
      title: 'Passwordverificationtoken',
    },
  },
  type: 'object',
  required: ['newEmail', 'passwordVerificationToken'],
  title: 'ChangeEmailGetOtpBody',
} as const;

export const $ChangeEmailGetOtpResponseApiModel = {
  properties: {
    retrySeconds: {
      type: 'integer',
      title: 'Retryseconds',
    },
    email: {
      type: 'string',
      title: 'Email',
    },
  },
  type: 'object',
  required: ['retrySeconds', 'email'],
  title: 'ChangeEmailGetOtpResponseApiModel',
} as const;

export const $ChangePasswordByOtpApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'ChangePasswordByOtpApiModel',
} as const;

export const $ChangePasswordByOtpBody = {
  properties: {
    otp: {
      type: 'string',
      title: 'Otp',
    },
    newPassword: {
      type: 'string',
      title: 'Newpassword',
    },
  },
  type: 'object',
  required: ['otp', 'newPassword'],
  title: 'ChangePasswordByOtpBody',
} as const;

export const $ChangePhoneByOtpBody = {
  properties: {
    otp: {
      type: 'string',
      title: 'Otp',
    },
  },
  type: 'object',
  required: ['otp'],
  title: 'ChangePhoneByOtpBody',
} as const;

export const $ChangePhoneByOtpResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'ChangePhoneByOtpResponseApiModel',
} as const;

export const $ChangePhoneGetOtpBody = {
  properties: {
    newPhoneNumber: {
      type: 'string',
      title: 'Newphonenumber',
    },
    passwordVerificationToken: {
      type: 'string',
      title: 'Passwordverificationtoken',
    },
  },
  type: 'object',
  required: ['newPhoneNumber', 'passwordVerificationToken'],
  title: 'ChangePhoneGetOtpBody',
} as const;

export const $ChangePhoneGetOtpResponseApiModel = {
  properties: {
    retrySeconds: {
      type: 'integer',
      title: 'Retryseconds',
    },
    phoneNumber: {
      type: 'string',
      title: 'Phonenumber',
    },
  },
  type: 'object',
  required: ['retrySeconds', 'phoneNumber'],
  title: 'ChangePhoneGetOtpResponseApiModel',
} as const;

export const $ChangeProfilePictureResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'ChangeProfilePictureResponseApiModel',
} as const;

export const $ChangeUsernameBody = {
  properties: {
    newUsername: {
      type: 'string',
      title: 'Newusername',
    },
    passwordVerificationToken: {
      type: 'string',
      title: 'Passwordverificationtoken',
    },
  },
  type: 'object',
  required: ['newUsername', 'passwordVerificationToken'],
  title: 'ChangeUsernameBody',
} as const;

export const $ChangeUsernameResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'ChangeUsernameResponseApiModel',
} as const;

export const $CreateDashboardForUserBody = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'CreateDashboardForUserBody',
} as const;

export const $CreateDashboardResponseApiModel = {
  properties: {
    createdDashboardId: {
      type: 'integer',
      title: 'Createddashboardid',
    },
    dashboards: {
      items: {
        $ref: '#/components/schemas/DashboardListItemApiModel',
      },
      type: 'array',
      title: 'Dashboards',
    },
  },
  type: 'object',
  required: ['createdDashboardId', 'dashboards'],
  title: 'CreateDashboardResponseApiModel',
} as const;

export const $DashboardDetailsApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    items: {
      items: {
        $ref: '#/components/schemas/DashboardItemApiModel',
      },
      type: 'array',
      title: 'Items',
    },
    funds: {
      items: {
        $ref: '#/components/schemas/DashboardFundApiModel',
      },
      type: 'array',
      title: 'Funds',
    },
    fundTypes: {
      items: {
        $ref: '#/components/schemas/DashboardFundTypeApiModel',
      },
      type: 'array',
      title: 'Fundtypes',
    },
    fundSortParameters: {
      items: {
        $ref: '#/components/schemas/DashboardFundSortParameterApiModel',
      },
      type: 'array',
      title: 'Fundsortparameters',
    },
    fundSortPeriods: {
      items: {
        $ref: '#/components/schemas/DashboardFundSortPeriodApiModel',
      },
      type: 'array',
      title: 'Fundsortperiods',
    },
    selectedFundTypeId: {
      type: 'integer',
      title: 'Selectedfundtypeid',
    },
    selectedFundSortParameterId: {
      type: 'integer',
      title: 'Selectedfundsortparameterid',
    },
    selectedFundSortPeriodId: {
      type: 'integer',
      title: 'Selectedfundsortperiodid',
    },
  },
  type: 'object',
  required: [
    'identifier',
    'name',
    'items',
    'funds',
    'fundTypes',
    'fundSortParameters',
    'fundSortPeriods',
    'selectedFundTypeId',
    'selectedFundSortParameterId',
    'selectedFundSortPeriodId',
  ],
  title: 'DashboardDetailsApiModel',
} as const;

export const $DashboardFundApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    registrationNumber: {
      type: 'integer',
      title: 'Registrationnumber',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    abbreviatedName: {
      type: 'string',
      title: 'Abbreviatedname',
    },
    parameterValue: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Parametervalue',
    },
    sparklineValues: {
      anyOf: [
        {
          items: {
            type: 'integer',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sparklinevalues',
    },
  },
  type: 'object',
  required: [
    'identifier',
    'registrationNumber',
    'name',
    'abbreviatedName',
    'parameterValue',
    'sparklineValues',
  ],
  title: 'DashboardFundApiModel',
} as const;

export const $DashboardFundSortParameterApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
  },
  type: 'object',
  required: ['identifier', 'title'],
  title: 'DashboardFundSortParameterApiModel',
} as const;

export const $DashboardFundSortPeriodApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
  },
  type: 'object',
  required: ['identifier', 'title'],
  title: 'DashboardFundSortPeriodApiModel',
} as const;

export const $DashboardFundTypeApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
  },
  type: 'object',
  required: ['identifier', 'title'],
  title: 'DashboardFundTypeApiModel',
} as const;

export const $DashboardItemApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    order: {
      type: 'integer',
      title: 'Order',
    },
    report: {
      $ref: '#/components/schemas/DashboardItemReportApiModel',
    },
    selectedFilters: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Selectedfilters',
    },
  },
  type: 'object',
  required: ['identifier', 'order', 'report', 'selectedFilters'],
  title: 'DashboardItemApiModel',
} as const;

export const $DashboardItemPreviewApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    order: {
      type: 'integer',
      title: 'Order',
    },
    reportPreview: {
      $ref: '#/components/schemas/DashboardReportPreviewApiModel',
    },
  },
  type: 'object',
  required: ['identifier', 'order', 'reportPreview'],
  title: 'DashboardItemPreviewApiModel',
} as const;

export const $DashboardItemReportApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
      description: 'Unique identifier of report',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    category: {
      $ref: '#/components/schemas/FinancialReportCategoryApiModel',
    },
    reportCalculation: {
      anyOf: [
        {
          $ref: '#/components/schemas/FinancialReportCalculationApiModel',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['identifier', 'title', 'category', 'reportCalculation'],
  title: 'DashboardItemReportApiModel',
} as const;

export const $DashboardItemScreenshotResponseApiModel = {
  properties: {
    queryId: {
      type: 'string',
      title: 'Queryid',
    },
    screenshotUrl: {
      type: 'string',
      title: 'Screenshoturl',
    },
  },
  type: 'object',
  required: ['queryId', 'screenshotUrl'],
  title: 'DashboardItemScreenshotResponseApiModel',
} as const;

export const $DashboardListItemApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
  },
  type: 'object',
  required: ['identifier', 'name'],
  title: 'DashboardListItemApiModel',
} as const;

export const $DashboardReportPreviewApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    image: {
      type: 'string',
      title: 'Image',
    },
  },
  type: 'object',
  required: ['identifier', 'title', 'image'],
  title: 'DashboardReportPreviewApiModel',
} as const;

export const $DeleteDashboardItemResponseApiModel = {
  properties: {},
  type: 'object',
  title: 'DeleteDashboardItemResponseApiModel',
} as const;

export const $DuplicateDashboardForUserBody = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'DuplicateDashboardForUserBody',
} as const;

export const $FinancialReportCalculationApiModel = {
  properties: {
    calculation: {
      anyOf: [
        {
          $ref: '#/components/schemas/Report2CalculationResult',
        },
        {
          $ref: '#/components/schemas/Report6CalculationResult',
        },
        {
          $ref: '#/components/schemas/Report13Dot1CalculationResult',
        },
        {
          $ref: '#/components/schemas/Report13Dot2CalculationResult',
        },
        {
          $ref: '#/components/schemas/Report13Dot3CalculationResult',
        },
        {
          $ref: '#/components/schemas/Report15CalculationResult',
        },
        {
          $ref: '#/components/schemas/Report36CalculationResult',
        },
        {
          $ref: '#/components/schemas/Report39CalculationResult',
        },
      ],
      title: 'Calculation',
    },
    filters: {
      items: {
        $ref: '#/components/schemas/FinancialReportFilterApiModel',
      },
      type: 'array',
      title: 'Filters',
    },
  },
  type: 'object',
  required: ['calculation', 'filters'],
  title: 'FinancialReportCalculationApiModel',
} as const;

export const $FinancialReportCategoryApiModel = {
  properties: {
    title: {
      type: 'string',
      title: 'Title',
    },
    identifier: {
      type: 'integer',
      title: 'Identifier',
      description: 'Unique identifier of report category',
    },
  },
  type: 'object',
  required: ['title', 'identifier'],
  title: 'FinancialReportCategoryApiModel',
} as const;

export const $FinancialReportDetailsApiModel = {
  properties: {
    identifier: {
      type: 'string',
      title: 'Identifier',
      description: 'Unique identifier of report',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    category: {
      $ref: '#/components/schemas/FinancialReportCategoryApiModel',
    },
    image: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Image',
    },
    summary: {
      type: 'string',
      title: 'Summary',
    },
    markdownDescription: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Markdowndescription',
    },
    video: {
      anyOf: [
        {
          $ref: '#/components/schemas/VideoApiModel',
        },
        {
          type: 'null',
        },
      ],
    },
    userFavorite: {
      type: 'boolean',
      title: 'Userfavorite',
      default: false,
    },
    isNew: {
      type: 'boolean',
      title: 'Isnew',
      default: false,
    },
    relatedReports: {
      items: {
        $ref: '#/components/schemas/FinancialReportListItemApiModel',
      },
      type: 'array',
      title: 'Relatedreports',
    },
    reportCalculation: {
      anyOf: [
        {
          $ref: '#/components/schemas/FinancialReportCalculationApiModel',
        },
        {
          type: 'null',
        },
      ],
    },
    screenshotUrl: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Screenshoturl',
    },
  },
  type: 'object',
  required: [
    'identifier',
    'title',
    'category',
    'image',
    'summary',
    'markdownDescription',
    'video',
    'relatedReports',
    'reportCalculation',
    'screenshotUrl',
  ],
  title: 'FinancialReportDetailsApiModel',
} as const;

export const $FinancialReportFilterApiModel = {
  properties: {
    parentTitle: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Parenttitle',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    searchable: {
      type: 'boolean',
      title: 'Searchable',
    },
    options: {
      items: {
        $ref: '#/components/schemas/FinancialReportFilterOptionDto',
      },
      type: 'array',
      title: 'Options',
    },
    selectedOption: {
      $ref: '#/components/schemas/FinancialReportFilterOptionDto',
    },
    optionType: {
      type: 'string',
      title: 'Optiontype',
    },
  },
  type: 'object',
  required: [
    'parentTitle',
    'title',
    'searchable',
    'options',
    'selectedOption',
    'optionType',
  ],
  title: 'FinancialReportFilterApiModel',
} as const;

export const $FinancialReportFilterOptionDto = {
  properties: {
    identifier: {
      type: 'string',
      title: 'Identifier',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
  },
  type: 'object',
  required: ['identifier', 'title'],
  title: 'FinancialReportFilterOptionDto',
} as const;

export const $FinancialReportListItemApiModel = {
  properties: {
    identifier: {
      type: 'string',
      title: 'Identifier',
      description: 'Unique identifier of report',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    category: {
      $ref: '#/components/schemas/FinancialReportCategoryApiModel',
    },
    image: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Image',
    },
    summary: {
      type: 'string',
      title: 'Summary',
    },
    hasVideo: {
      type: 'boolean',
      title: 'Hasvideo',
      default: false,
    },
    userFavorite: {
      type: 'boolean',
      title: 'Userfavorite',
      default: false,
    },
    isNew: {
      type: 'boolean',
      title: 'Isnew',
      default: false,
    },
  },
  type: 'object',
  required: ['identifier', 'title', 'category', 'image', 'summary'],
  title: 'FinancialReportListItemApiModel',
} as const;

export const $ForgotPasswordResetByOtpBody = {
  properties: {
    otp: {
      type: 'string',
      title: 'Otp',
    },
    newPassword: {
      type: 'string',
      title: 'Newpassword',
    },
    userId: {
      type: 'integer',
      title: 'Userid',
    },
  },
  type: 'object',
  required: ['otp', 'newPassword', 'userId'],
  title: 'ForgotPasswordResetByOtpBody',
} as const;

export const $FundListItemApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
      description: 'شناسه صندوق',
    },
    registrationNumber: {
      type: 'integer',
      title: 'Registrationnumber',
      description: 'شماره ثبت نزد سازمان بورس',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'نام کامل صندوق',
    },
    abbreviatedName: {
      type: 'string',
      title: 'Abbreviatedname',
      description: 'نام صندوق',
    },
    fundType: {
      $ref: '#/components/schemas/FundTypeApiModel',
      description: 'نوع صندوق',
    },
    logoMedium: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Logomedium',
      description: 'آدرس لوگوی صندوق - سایز متوسط',
    },
    logoThumbnail: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Logothumbnail',
      description: 'آدرس لوگوی صندوق - سایز کوچک',
    },
    website: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Website',
      description: 'وبسایت صندوق',
    },
    statuteUrl: {
      type: 'string',
      title: 'Statuteurl',
      description: 'اساسنامه صندوق',
    },
    prospectusUrl: {
      type: 'string',
      title: 'Prospectusurl',
      description: 'امیدنامه صندوق',
    },
    isEtf: {
      type: 'boolean',
      title: 'Isetf',
      description: 'آیا صندوق etf است',
    },
    isCharity: {
      type: 'boolean',
      title: 'Ischarity',
      description: 'آیا صندوق نیکوکاری است',
    },
    hasVideo: {
      type: 'boolean',
      title: 'Hasvideo',
      description: 'دارای ویدیو بررسی',
    },
    manager: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Manager',
      description: 'مدیر صنودق',
    },
    custodian: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Custodian',
      description: 'متولی صندوق',
    },
    auditor: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Auditor',
      description: 'حسابرس صندوق',
    },
    liquidityGuarantor: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Liquidityguarantor',
      description: 'ضامن نقد شوندگی صندوق',
    },
    marketMaker: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Marketmaker',
      description: 'بازارگردان',
    },
    initiationDate: {
      type: 'string',
      title: 'Initiationdate',
      description: 'تاریخ آغاز فعالیت میلادی',
    },
    initiationJdate: {
      type: 'string',
      title: 'Initiationjdate',
      description: 'تاریخ آغاز فعالیت',
    },
  },
  type: 'object',
  required: [
    'identifier',
    'registrationNumber',
    'name',
    'abbreviatedName',
    'fundType',
    'logoMedium',
    'logoThumbnail',
    'website',
    'statuteUrl',
    'prospectusUrl',
    'isEtf',
    'isCharity',
    'hasVideo',
    'manager',
    'custodian',
    'auditor',
    'liquidityGuarantor',
    'marketMaker',
    'initiationDate',
    'initiationJdate',
  ],
  title: 'FundListItemApiModel',
} as const;

export const $FundTableItemInfoApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
      description: 'شناسه صندوق',
    },
    registrationNumber: {
      type: 'integer',
      title: 'Registrationnumber',
      description: 'شماره ثبت نزد سازمان بورس',
    },
    name: {
      type: 'string',
      title: 'Name',
      description: 'نام کامل صندوق',
    },
    abbreviatedName: {
      type: 'string',
      title: 'Abbreviatedname',
      description: 'نام صندوق',
    },
    fundType: {
      $ref: '#/components/schemas/FundTypeApiModel',
      description: 'نوع صندوق',
    },
    logoMedium: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Logomedium',
      description: 'آدرس لوگوی صندوق - سایز متوسط',
    },
    logoThumbnail: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Logothumbnail',
      description: 'آدرس لوگوی صندوق - سایز کوچک',
    },
    website: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Website',
      description: 'وبسایت صندوق',
    },
    statuteUrl: {
      type: 'string',
      title: 'Statuteurl',
      description: 'اساسنامه صندوق',
    },
    prospectusUrl: {
      type: 'string',
      title: 'Prospectusurl',
      description: 'امیدنامه صندوق',
    },
    isEtf: {
      type: 'boolean',
      title: 'Isetf',
      description: 'آیا صندوق etf است',
    },
    isCharity: {
      type: 'boolean',
      title: 'Ischarity',
      description: 'آیا صندوق نیکوکاری است',
    },
    hasVideo: {
      type: 'boolean',
      title: 'Hasvideo',
      description: 'دارای ویدیو بررسی',
    },
    manager: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Manager',
      description: 'مدیر صنودق',
    },
    custodian: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Custodian',
      description: 'متولی صندوق',
    },
    auditor: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Auditor',
      description: 'حسابرس صندوق',
    },
    liquidityGuarantor: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Liquidityguarantor',
      description: 'ضامن نقد شوندگی صندوق',
    },
    marketMaker: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Marketmaker',
      description: 'بازارگردان',
    },
    initiationDate: {
      type: 'string',
      title: 'Initiationdate',
      description: 'تاریخ آغاز فعالیت میلادی',
    },
    initiationJdate: {
      type: 'string',
      title: 'Initiationjdate',
      description: 'تاریخ آغاز فعالیت',
    },
    issueNavRials: {
      type: 'integer',
      title: 'Issuenavrials',
      description: 'قیمت صدور (ریال)',
    },
    redeemNavRials: {
      type: 'integer',
      title: 'Redeemnavrials',
      description: 'قیمت ابطال (ریال)',
    },
    statisticalNavRials: {
      type: 'integer',
      title: 'Statisticalnavrials',
      description: 'قیمت آماری (ریال)',
    },
    assetUnderManagementRials: {
      type: 'integer',
      title: 'Assetundermanagementrials',
      description: 'کل ارزش خالص دارایی‌ها (ریال)',
    },
    numberOfUnits: {
      type: 'integer',
      title: 'Numberofunits',
      description: 'تعداد واحد',
    },
    returnLastDayPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnlastdaypercent',
      description: 'بازده روزانه',
    },
    returnLastWeekPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnlastweekpercent',
      description: 'بازده هفتگی',
    },
    returnLastMonthPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnlastmonthpercent',
      description: 'بازده ماهانه',
    },
    returnLast3MonthsPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnlast3Monthspercent',
      description: 'بازده سه‌ماهه',
    },
    returnLastYearPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnlastyearpercent',
      description: 'بازده یک‌ساله',
    },
    returnCustomPeriodPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returncustomperiodpercent',
      description: 'بازده بازه دلخواه',
    },
    returnVsTedpixLastDayPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnvstedpixlastdaypercent',
      description: 'بازده نسبت به شاخص روزانه',
    },
    returnVsTedpixLastWeekPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnvstedpixlastweekpercent',
      description: 'بازده نسبت به شاخص هفتگی',
    },
    returnVsTedpixLastMonthPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnvstedpixlastmonthpercent',
      description: 'بازده نسبت به شاخص ماهانه',
    },
    returnVsTedpixLast3MonthsPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnvstedpixlast3Monthspercent',
      description: 'بازده نسبت به شاخص سه‌ماهه',
    },
    returnVsTedpixLastYearPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnvstedpixlastyearpercent',
      description: 'بازده نسبت به شاخص یک‌ساله',
    },
    returnVsTedpixCustomPeriodPercent: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Returnvstedpixcustomperiodpercent',
      description: 'بازده نسبت به شاخص بازه دلخواه',
    },
    assetAllocationBondPercent: {
      type: 'number',
      title: 'Assetallocationbondpercent',
      description: 'سهم اوراق از پورتفوی',
    },
    assetAllocationBankDepositPercent: {
      type: 'number',
      title: 'Assetallocationbankdepositpercent',
      description: 'سهم سپرده بانکی از پورتفوی',
    },
    assetAllocationCommodityDepositCertificatePercent: {
      type: 'number',
      title: 'Assetallocationcommoditydepositcertificatepercent',
      description: 'سهم گواهی سپرده کالایی از پورتفوی',
    },
    assetAllocationCashPercent: {
      type: 'number',
      title: 'Assetallocationcashpercent',
      description: 'سهم وجه نقد از پورتفوی',
    },
    assetAllocationStocksIncludingTop5Percent: {
      type: 'number',
      title: 'Assetallocationstocksincludingtop5Percent',
      description: 'سهم سهام از پورتفوی',
    },
    assetAllocationFundUnitsPercent: {
      type: 'number',
      title: 'Assetallocationfundunitspercent',
      description: 'سهم واحد صندوق‌ها از پورتفوی',
    },
    assetAllocationOtherPercent: {
      type: 'number',
      title: 'Assetallocationotherpercent',
      description: 'سهم سایر از پورتفوی',
    },
    assetAllocationTop5StocksPercent: {
      type: 'number',
      title: 'Assetallocationtop5Stockspercent',
      description: 'سهم پنج سهم برتر از پورتفوی',
    },
    averageLeverageLastWeek: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Averageleveragelastweek',
      description: 'میانگین اهرم هتگی',
    },
    averageLeverageLastMonth: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Averageleveragelastmonth',
      description: 'میانگین اهرم ماهانه',
    },
    averageLeverageLast3Months: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Averageleveragelast3Months',
      description: 'میانگین اهرم سه‌ماهه',
    },
    averageLeverageLastYear: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Averageleveragelastyear',
      description: 'میانگین اهرم یک‌ساله',
    },
    averageLeverageCustomPeriod: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Averageleveragecustomperiod',
      description: 'میانگین اهرم بازه دلخواه',
    },
    standardDeviationLastWeek: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Standarddeviationlastweek',
      description: 'انحراف از میانگین هتگی',
    },
    standardDeviationLastMonth: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Standarddeviationlastmonth',
      description: 'انحراف از میانگین ماهانه',
    },
    standardDeviationLast3Month: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Standarddeviationlast3Month',
      description: 'انحراف از میانگین سه‌ماهه',
    },
    standardDeviationLastYear: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Standarddeviationlastyear',
      description: 'انحراف از میانگین یک‌ساله',
    },
    standardDeviationCustomPeriod: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Standarddeviationcustomperiod',
      description: 'انحراف از میانگین بازه دلخواه',
    },
    sharpeRatioLastWeek: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sharperatiolastweek',
      description: 'نسبت شارپی هفتگی',
    },
    sharpeRatioLastMonth: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sharperatiolastmonth',
      description: 'نسبت شارپی ماهانه',
    },
    sharpeRatioLast3Months: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sharperatiolast3Months',
      description: 'نسبت شارپی سه‌ماهه',
    },
    sharpeRatioLastYear: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sharperatiolastyear',
      description: 'نسبت شارپی یک‌ساله',
    },
    sharpeRatioCustomPeriod: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Sharperatiocustomperiod',
      description: 'نسبت شارپی بازه دلخواه',
    },
    informationRatioLastWeek: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Informationratiolastweek',
      description: 'نسبت اصلاعاتی هفتگی',
    },
    informationRatioLastMonth: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Informationratiolastmonth',
      description: 'نسبت اصلاعاتی ماهانه',
    },
    informationRatioLast3Months: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Informationratiolast3Months',
      description: 'نسبت اصلاعاتی سه‌ماهه',
    },
    informationRatioLastYear: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Informationratiolastyear',
      description: 'نسبت اصلاعاتی یک‌ساله',
    },
    informationRatioCustomPeriod: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Informationratiocustomperiod',
      description: 'نسبت اصلاعاتی بازه دلخواه',
    },
    alphaLastDay: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Alphalastday',
      description: 'آلفا روزانه',
    },
    alphaLastWeek: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Alphalastweek',
      description: 'آلفا هفتگی',
    },
    alphaLastMonth: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Alphalastmonth',
      description: 'آلفا ماهانه',
    },
    alphaLast3Months: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Alphalast3Months',
      description: 'آلفا سه‌ماهه',
    },
    alphaLastYear: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Alphalastyear',
      description: 'آلفا یک‌ساله',
    },
    alphaCustomPeriod: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Alphacustomperiod',
      description: 'آلفا بازه دلخواه',
    },
    betaLastDay: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Betalastday',
      description: 'بتا روزانه',
    },
    betaLastWeek: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Betalastweek',
      description: 'بتا هفتگی',
    },
    betaLastMonth: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Betalastmonth',
      description: 'بتا ماهانه',
    },
    betaLast3Months: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Betalast3Months',
      description: 'بتا سه‌ماهه',
    },
    betaLastYear: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Betalastyear',
      description: 'بتا یک‌سساله',
    },
    betaCustomPeriod: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Betacustomperiod',
      description: 'بتا بازه دلخواه',
    },
    maxDrawdownWeek: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Maxdrawdownweek',
      description: 'بیشترین ریزش هفتگی',
    },
    maxDrawdownMonth: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Maxdrawdownmonth',
      description: 'بیشترین ریزش ماهانه',
    },
    maxDrawdown3Month: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Maxdrawdown3Month',
      description: 'بیشترین ریزش سه‌ماهه',
    },
    maxDrawdownYear: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Maxdrawdownyear',
      description: 'بیشترین ریزش یک‌ساله',
    },
    maxDrawdownCustomPeriod: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Maxdrawdowncustomperiod',
      description: 'بیشترین ریزش بازه دلخواه',
    },
  },
  type: 'object',
  required: [
    'identifier',
    'registrationNumber',
    'name',
    'abbreviatedName',
    'fundType',
    'logoMedium',
    'logoThumbnail',
    'website',
    'statuteUrl',
    'prospectusUrl',
    'isEtf',
    'isCharity',
    'hasVideo',
    'manager',
    'custodian',
    'auditor',
    'liquidityGuarantor',
    'marketMaker',
    'initiationDate',
    'initiationJdate',
    'issueNavRials',
    'redeemNavRials',
    'statisticalNavRials',
    'assetUnderManagementRials',
    'numberOfUnits',
    'returnLastDayPercent',
    'returnLastWeekPercent',
    'returnLastMonthPercent',
    'returnLast3MonthsPercent',
    'returnLastYearPercent',
    'returnCustomPeriodPercent',
    'returnVsTedpixLastDayPercent',
    'returnVsTedpixLastWeekPercent',
    'returnVsTedpixLastMonthPercent',
    'returnVsTedpixLast3MonthsPercent',
    'returnVsTedpixLastYearPercent',
    'returnVsTedpixCustomPeriodPercent',
    'assetAllocationBondPercent',
    'assetAllocationBankDepositPercent',
    'assetAllocationCommodityDepositCertificatePercent',
    'assetAllocationCashPercent',
    'assetAllocationStocksIncludingTop5Percent',
    'assetAllocationFundUnitsPercent',
    'assetAllocationOtherPercent',
    'assetAllocationTop5StocksPercent',
    'averageLeverageLastWeek',
    'averageLeverageLastMonth',
    'averageLeverageLast3Months',
    'averageLeverageLastYear',
    'averageLeverageCustomPeriod',
    'standardDeviationLastWeek',
    'standardDeviationLastMonth',
    'standardDeviationLast3Month',
    'standardDeviationLastYear',
    'standardDeviationCustomPeriod',
    'sharpeRatioLastWeek',
    'sharpeRatioLastMonth',
    'sharpeRatioLast3Months',
    'sharpeRatioLastYear',
    'sharpeRatioCustomPeriod',
    'informationRatioLastWeek',
    'informationRatioLastMonth',
    'informationRatioLast3Months',
    'informationRatioLastYear',
    'informationRatioCustomPeriod',
    'alphaLastDay',
    'alphaLastWeek',
    'alphaLastMonth',
    'alphaLast3Months',
    'alphaLastYear',
    'alphaCustomPeriod',
    'betaLastDay',
    'betaLastWeek',
    'betaLastMonth',
    'betaLast3Months',
    'betaLastYear',
    'betaCustomPeriod',
    'maxDrawdownWeek',
    'maxDrawdownMonth',
    'maxDrawdown3Month',
    'maxDrawdownYear',
    'maxDrawdownCustomPeriod',
  ],
  title: 'FundTableItemInfoApiModel',
} as const;

export const $FundTableResponseApiModel = {
  properties: {
    tabs: {
      items: {
        $ref: '#/components/schemas/FundTableTabApiModel',
      },
      type: 'array',
      title: 'Tabs',
    },
    selectedTabIdentifier: {
      type: 'integer',
      title: 'Selectedtabidentifier',
    },
    selectedTabFunds: {
      items: {
        $ref: '#/components/schemas/FundsTableItemApiModel',
      },
      type: 'array',
      title: 'Selectedtabfunds',
    },
    columns: {
      items: {
        $ref: '#/components/schemas/FundTableTabColumnDto',
      },
      type: 'array',
      title: 'Columns',
    },
    columnGroups: {
      items: {
        $ref: '#/components/schemas/FundTableTabColumnGroupDto',
      },
      type: 'array',
      title: 'Columngroups',
    },
  },
  type: 'object',
  required: [
    'tabs',
    'selectedTabIdentifier',
    'selectedTabFunds',
    'columns',
    'columnGroups',
  ],
  title: 'FundTableResponseApiModel',
} as const;

export const $FundTableTabApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
    color: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Color',
    },
  },
  type: 'object',
  required: ['identifier', 'title', 'color'],
  title: 'FundTableTabApiModel',
} as const;

export const $FundTableTabColumnColorFormat = {
  type: 'string',
  enum: ['NOT_COLORED', 'COLORED'],
  title: 'FundTableTabColumnColorFormat',
} as const;

export const $FundTableTabColumnDto = {
  properties: {
    label: {
      type: 'string',
      title: 'Label',
    },
    upperTitle: {
      type: 'string',
      title: 'Uppertitle',
    },
    lowerTitle: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lowertitle',
    },
    key: {
      type: 'string',
      title: 'Key',
    },
    visible: {
      type: 'boolean',
      title: 'Visible',
    },
    sort: {
      $ref: '#/components/schemas/FundTableTabColumnSort',
    },
    colorFormat: {
      $ref: '#/components/schemas/FundTableTabColumnColorFormat',
    },
    columnFilter: {
      anyOf: [
        {
          $ref: '#/components/schemas/FundTableTabColumnFilterTextDto',
        },
        {
          $ref: '#/components/schemas/FundTableTabColumnFilterOptionsDto',
        },
        {
          type: 'null',
        },
      ],
      title: 'Columnfilter',
    },
    columnGroupId: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Columngroupid',
    },
    customPeriodStartJdate: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Customperiodstartjdate',
    },
    customPeriodEndJdate: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Customperiodendjdate',
    },
  },
  type: 'object',
  required: [
    'label',
    'upperTitle',
    'lowerTitle',
    'key',
    'visible',
    'sort',
    'colorFormat',
    'columnGroupId',
    'customPeriodStartJdate',
    'customPeriodEndJdate',
  ],
  title: 'FundTableTabColumnDto',
} as const;

export const $FundTableTabColumnFilterOptionDto = {
  properties: {
    identifier: {
      type: 'string',
      title: 'Identifier',
    },
    label: {
      type: 'string',
      title: 'Label',
    },
    selected: {
      type: 'boolean',
      title: 'Selected',
    },
  },
  type: 'object',
  required: ['identifier', 'label', 'selected'],
  title: 'FundTableTabColumnFilterOptionDto',
} as const;

export const $FundTableTabColumnFilterOptionsDto = {
  properties: {
    options: {
      items: {
        $ref: '#/components/schemas/FundTableTabColumnFilterOptionDto',
      },
      type: 'array',
      title: 'Options',
    },
  },
  type: 'object',
  required: ['options'],
  title: 'FundTableTabColumnFilterOptionsDto',
} as const;

export const $FundTableTabColumnFilterTextDto = {
  properties: {
    filter_text: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Filter Text',
    },
  },
  type: 'object',
  required: ['filter_text'],
  title: 'FundTableTabColumnFilterTextDto',
} as const;

export const $FundTableTabColumnGroupDto = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    label: {
      type: 'string',
      title: 'Label',
    },
  },
  type: 'object',
  required: ['identifier', 'label'],
  title: 'FundTableTabColumnGroupDto',
} as const;

export const $FundTableTabColumnSort = {
  type: 'string',
  enum: ['NO', 'ASC', 'DESC'],
  title: 'FundTableTabColumnSort',
} as const;

export const $FundTypeApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
    },
    title: {
      type: 'string',
      title: 'Title',
    },
  },
  type: 'object',
  required: ['identifier', 'title'],
  title: 'FundTypeApiModel',
} as const;

export const $FundsTableItemApiModel = {
  properties: {
    info: {
      $ref: '#/components/schemas/FundTableItemInfoApiModel',
    },
    pinned: {
      type: 'boolean',
      title: 'Pinned',
    },
    mark: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mark',
    },
  },
  type: 'object',
  required: ['info', 'pinned', 'mark'],
  title: 'FundsTableItemApiModel',
} as const;

export const $GetDashboardItemCalculationsBody = {
  properties: {
    selectedFilters: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Selectedfilters',
    },
  },
  type: 'object',
  title: 'GetDashboardItemCalculationsBody',
} as const;

export const $GetForgotPasswordOtpBody = {
  properties: {
    nationalCode: {
      type: 'string',
      title: 'Nationalcode',
    },
    phoneNumber: {
      type: 'string',
      title: 'Phonenumber',
    },
    captchaUid: {
      type: 'integer',
      title: 'Captchauid',
    },
    captchaValue: {
      type: 'string',
      title: 'Captchavalue',
    },
  },
  type: 'object',
  required: ['nationalCode', 'phoneNumber', 'captchaUid', 'captchaValue'],
  title: 'GetForgotPasswordOtpBody',
} as const;

export const $GetOtpForChangePasswordResponseApiModel = {
  properties: {
    retrySeconds: {
      type: 'integer',
      title: 'Retryseconds',
    },
    phoneNumber: {
      type: 'string',
      title: 'Phonenumber',
    },
    userId: {
      type: 'integer',
      title: 'Userid',
    },
  },
  type: 'object',
  required: ['retrySeconds', 'phoneNumber', 'userId'],
  title: 'GetOtpForChangePasswordResponseApiModel',
} as const;

export const $GetOtpForForgotPasswordResponseApiModel = {
  properties: {
    retrySeconds: {
      type: 'integer',
      title: 'Retryseconds',
    },
    phoneNumber: {
      type: 'string',
      title: 'Phonenumber',
    },
    userId: {
      type: 'integer',
      title: 'Userid',
    },
  },
  type: 'object',
  required: ['retrySeconds', 'phoneNumber', 'userId'],
  title: 'GetOtpForForgotPasswordResponseApiModel',
} as const;

export const $GetReportCalculationsBody = {
  properties: {
    selectedFilters: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Selectedfilters',
    },
  },
  type: 'object',
  required: ['selectedFilters'],
  title: 'GetReportCalculationsBody',
} as const;

export const $HealthApiModel = {
  properties: {
    status: {
      type: 'string',
      title: 'Status',
    },
  },
  type: 'object',
  required: ['status'],
  title: 'HealthApiModel',
} as const;

export const $LogoutResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'LogoutResponseApiModel',
} as const;

export const $MarkFundBody = {
  properties: {
    color: {
      type: 'string',
      title: 'Color',
    },
  },
  type: 'object',
  required: ['color'],
  title: 'MarkFundBody',
} as const;

export const $MarkFundResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'MarkFundResponseApiModel',
} as const;

export const $PinFundInTableTabBody = {
  properties: {
    fund: {
      type: 'integer',
      title: 'Fund',
    },
  },
  type: 'object',
  required: ['fund'],
  title: 'PinFundInTableTabBody',
} as const;

export const $PinFundInTableTabResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'PinFundInTableTabResponseApiModel',
} as const;

export const $RemoveFundFromWatchListResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'RemoveFundFromWatchListResponseApiModel',
} as const;

export const $RenameDashboardForUserBody = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
  },
  type: 'object',
  required: ['name'],
  title: 'RenameDashboardForUserBody',
} as const;

export const $ReplaceDashboardItemCalculationsBody = {
  properties: {
    newReportIdentifier: {
      type: 'string',
      title: 'Newreportidentifier',
    },
  },
  type: 'object',
  required: ['newReportIdentifier'],
  title: 'ReplaceDashboardItemCalculationsBody',
} as const;

export const $Report13Dot1CalculationResult = {
  properties: {
    lastDay: {
      $ref: '#/components/schemas/Report13Dot1CalculationResultColumn',
    },
    lastDayNormalized: {
      $ref: '#/components/schemas/Report13Dot1CalculationResultColumnNormalized',
    },
    maxValue: {
      $ref: '#/components/schemas/Report13Dot1CalculationResultColumn',
    },
    minValue: {
      $ref: '#/components/schemas/Report13Dot1CalculationResultColumn',
    },
    averageValue: {
      $ref: '#/components/schemas/Report13Dot1CalculationResultColumn',
    },
    currencyUnit: {
      type: 'string',
      title: 'Currencyunit',
    },
  },
  type: 'object',
  required: [
    'lastDay',
    'lastDayNormalized',
    'maxValue',
    'minValue',
    'averageValue',
    'currencyUnit',
  ],
  title: 'Report13Dot1CalculationResult',
} as const;

export const $Report13Dot1CalculationResultColumn = {
  properties: {
    totalTrades: {
      type: 'number',
      title: 'Totaltrades',
    },
    totalBuyIndividual: {
      type: 'number',
      title: 'Totalbuyindividual',
    },
    totalBuyCorporate: {
      type: 'number',
      title: 'Totalbuycorporate',
    },
    totalSellIndividual: {
      type: 'number',
      title: 'Totalsellindividual',
    },
    totalSellCorporate: {
      type: 'number',
      title: 'Totalsellcorporate',
    },
  },
  type: 'object',
  required: [
    'totalTrades',
    'totalBuyIndividual',
    'totalBuyCorporate',
    'totalSellIndividual',
    'totalSellCorporate',
  ],
  title: 'Report13Dot1CalculationResultColumn',
} as const;

export const $Report13Dot1CalculationResultColumnNormalized = {
  properties: {
    totalTradesNormalized: {
      type: 'number',
      title: 'Totaltradesnormalized',
    },
    totalBuyIndividualNormalized: {
      type: 'number',
      title: 'Totalbuyindividualnormalized',
    },
    totalBuyCorporateNormalized: {
      type: 'number',
      title: 'Totalbuycorporatenormalized',
    },
    totalSellIndividualNormalized: {
      type: 'number',
      title: 'Totalsellindividualnormalized',
    },
    totalSellCorporateNormalized: {
      type: 'number',
      title: 'Totalsellcorporatenormalized',
    },
  },
  type: 'object',
  required: [
    'totalTradesNormalized',
    'totalBuyIndividualNormalized',
    'totalBuyCorporateNormalized',
    'totalSellIndividualNormalized',
    'totalSellCorporateNormalized',
  ],
  title: 'Report13Dot1CalculationResultColumnNormalized',
} as const;

export const $Report13Dot2CalculationResult = {
  properties: {
    data: {
      $ref: '#/components/schemas/Report13Dot2CalculationResultItem',
    },
  },
  type: 'object',
  required: ['data'],
  title: 'Report13Dot2CalculationResult',
} as const;

export const $Report13Dot2CalculationResultItem = {
  properties: {
    mean: {
      type: 'number',
      title: 'Mean',
    },
    median: {
      type: 'number',
      title: 'Median',
    },
    lastTrade: {
      type: 'number',
      title: 'Lasttrade',
    },
    kdePoints: {
      items: {
        $ref: '#/components/schemas/Report13Dot2GraphKdeResultItem',
      },
      type: 'array',
      title: 'Kdepoints',
    },
    histPoints: {
      items: {
        $ref: '#/components/schemas/Report13Dot2GraphHistResultItem',
      },
      type: 'array',
      title: 'Histpoints',
    },
  },
  type: 'object',
  required: ['mean', 'median', 'lastTrade', 'kdePoints', 'histPoints'],
  title: 'Report13Dot2CalculationResultItem',
} as const;

export const $Report13Dot2GraphHistResultItem = {
  properties: {
    xMin: {
      type: 'number',
      title: 'Xmin',
    },
    xMax: {
      type: 'number',
      title: 'Xmax',
    },
    y: {
      type: 'number',
      title: 'Y',
    },
  },
  type: 'object',
  required: ['xMin', 'xMax', 'y'],
  title: 'Report13Dot2GraphHistResultItem',
} as const;

export const $Report13Dot2GraphKdeResultItem = {
  properties: {
    x: {
      type: 'number',
      title: 'X',
    },
    y: {
      type: 'number',
      title: 'Y',
    },
  },
  type: 'object',
  required: ['x', 'y'],
  title: 'Report13Dot2GraphKdeResultItem',
} as const;

export const $Report13Dot3CalculationResult = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/Report13Dot3CalculationResultItem',
      },
      type: 'array',
      title: 'Data',
    },
  },
  type: 'object',
  required: ['data'],
  title: 'Report13Dot3CalculationResult',
} as const;

export const $Report13Dot3CalculationResultItem = {
  properties: {
    points: {
      items: {
        $ref: '#/components/schemas/Report13Dot3CalculationResultPoints',
      },
      type: 'array',
      title: 'Points',
    },
    mean: {
      type: 'number',
      title: 'Mean',
    },
  },
  type: 'object',
  required: ['points', 'mean'],
  title: 'Report13Dot3CalculationResultItem',
} as const;

export const $Report13Dot3CalculationResultPoints = {
  properties: {
    date: {
      type: 'string',
      title: 'Date',
    },
    value: {
      type: 'number',
      title: 'Value',
    },
  },
  type: 'object',
  required: ['date', 'value'],
  title: 'Report13Dot3CalculationResultPoints',
} as const;

export const $Report15CalculationResult = {
  properties: {
    beta: {
      type: 'number',
      title: 'Beta',
    },
    betaAdjusted: {
      type: 'number',
      title: 'Betaadjusted',
    },
    yIntersect: {
      type: 'number',
      title: 'Yintersect',
    },
    rSquared: {
      type: 'number',
      title: 'Rsquared',
    },
    pValue: {
      type: 'number',
      title: 'Pvalue',
    },
    graphData: {
      items: {
        $ref: '#/components/schemas/Report15CalculationResultGraphPoint',
      },
      type: 'array',
      title: 'Graphdata',
    },
  },
  type: 'object',
  required: [
    'beta',
    'betaAdjusted',
    'yIntersect',
    'rSquared',
    'pValue',
    'graphData',
  ],
  title: 'Report15CalculationResult',
} as const;

export const $Report15CalculationResultGraphPoint = {
  properties: {
    x: {
      type: 'number',
      title: 'X',
    },
    y: {
      type: 'number',
      title: 'Y',
    },
    tradeDateShamsi: {
      type: 'string',
      title: 'Tradedateshamsi',
    },
  },
  type: 'object',
  required: ['x', 'y', 'tradeDateShamsi'],
  title: 'Report15CalculationResultGraphPoint',
} as const;

export const $Report2CalculationResult = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/Report2CalculationResultItem',
      },
      type: 'array',
      title: 'Data',
    },
    unit: {
      type: 'string',
      title: 'Unit',
    },
  },
  type: 'object',
  required: ['data', 'unit'],
  title: 'Report2CalculationResult',
} as const;

export const $Report2CalculationResultItem = {
  properties: {
    sectorTitle: {
      type: 'string',
      title: 'Sectortitle',
    },
    netFlow: {
      type: 'number',
      title: 'Netflow',
    },
  },
  type: 'object',
  required: ['sectorTitle', 'netFlow'],
  title: 'Report2CalculationResultItem',
} as const;

export const $Report36CalculationResult = {
  properties: {
    buckets: {
      items: {
        $ref: '#/components/schemas/Report36CalculationResultBucket',
      },
      type: 'array',
      title: 'Buckets',
    },
    positiveInstruments: {
      type: 'integer',
      title: 'Positiveinstruments',
    },
    negativeInstruments: {
      type: 'integer',
      title: 'Negativeinstruments',
    },
    bucketRangeUnit: {
      type: 'string',
      title: 'Bucketrangeunit',
    },
    bucketCountUnit: {
      type: 'string',
      title: 'Bucketcountunit',
    },
  },
  type: 'object',
  required: [
    'buckets',
    'positiveInstruments',
    'negativeInstruments',
    'bucketRangeUnit',
    'bucketCountUnit',
  ],
  title: 'Report36CalculationResult',
} as const;

export const $Report36CalculationResultBucket = {
  properties: {
    bucketMin: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Bucketmin',
    },
    bucketMax: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Bucketmax',
    },
    displayBucketAverage: {
      type: 'number',
      title: 'Displaybucketaverage',
    },
    bucketInstrumentsCount: {
      type: 'integer',
      title: 'Bucketinstrumentscount',
    },
  },
  type: 'object',
  required: [
    'bucketMin',
    'bucketMax',
    'displayBucketAverage',
    'bucketInstrumentsCount',
  ],
  title: 'Report36CalculationResultBucket',
} as const;

export const $Report39CalculationResult = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/Report39InstrumentsResultItem',
      },
      type: 'array',
      title: 'Data',
    },
    unit: {
      type: 'string',
      title: 'Unit',
    },
  },
  type: 'object',
  required: ['data', 'unit'],
  title: 'Report39CalculationResult',
} as const;

export const $Report39InstrumentsResultItem = {
  properties: {
    instrument: {
      type: 'string',
      title: 'Instrument',
    },
    netFlow: {
      type: 'number',
      title: 'Netflow',
    },
  },
  type: 'object',
  required: ['instrument', 'netFlow'],
  title: 'Report39InstrumentsResultItem',
} as const;

export const $Report6CalculationResult = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/Report6CalculationResultTimeSeriesItem',
      },
      type: 'array',
      title: 'Data',
    },
    indexUnit: {
      type: 'string',
      title: 'Indexunit',
    },
    netFlowUnit: {
      type: 'string',
      title: 'Netflowunit',
    },
  },
  type: 'object',
  required: ['data', 'indexUnit', 'netFlowUnit'],
  title: 'Report6CalculationResult',
} as const;

export const $Report6CalculationResultTimeSeriesItem = {
  properties: {
    dt: {
      type: 'string',
      title: 'Dt',
    },
    indexValue: {
      type: 'number',
      title: 'Indexvalue',
    },
    netFlow: {
      type: 'number',
      title: 'Netflow',
    },
  },
  type: 'object',
  required: ['dt', 'indexValue', 'netFlow'],
  title: 'Report6CalculationResultTimeSeriesItem',
} as const;

export const $ReportScreenshotResponseApiModel = {
  properties: {
    queryId: {
      type: 'string',
      title: 'Queryid',
    },
    screenshotUrl: {
      type: 'string',
      title: 'Screenshoturl',
    },
  },
  type: 'object',
  required: ['queryId', 'screenshotUrl'],
  title: 'ReportScreenshotResponseApiModel',
} as const;

export const $RequestReportForm = {
  properties: {
    title: {
      type: 'string',
      title: 'Title',
    },
    text: {
      type: 'string',
      title: 'Text',
    },
    call: {
      type: 'string',
      title: 'Call',
    },
  },
  type: 'object',
  required: ['title', 'text', 'call'],
  title: 'RequestReportForm',
} as const;

export const $RequestReportResponseApiModel = {
  properties: {
    requestFollowCode: {
      type: 'integer',
      title: 'Requestfollowcode',
    },
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['requestFollowCode', 'success'],
  title: 'RequestReportResponseApiModel',
} as const;

export const $ResetForgotPasswordByOtpResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'ResetForgotPasswordByOtpResponseApiModel',
} as const;

export const $SortFundTabBody = {
  properties: {
    columnKey: {
      type: 'string',
      title: 'Columnkey',
    },
    direction: {
      $ref: '#/components/schemas/FundTableTabColumnSort',
    },
  },
  type: 'object',
  required: ['columnKey', 'direction'],
  title: 'SortFundTabBody',
} as const;

export const $SortFundTabResponseApiModel = {
  properties: {
    funds: {
      items: {
        $ref: '#/components/schemas/FundsTableItemApiModel',
      },
      type: 'array',
      title: 'Funds',
    },
    columns: {
      items: {
        $ref: '#/components/schemas/FundTableTabColumnDto',
      },
      type: 'array',
      title: 'Columns',
    },
  },
  type: 'object',
  required: ['funds', 'columns'],
  title: 'SortFundTabResponseApiModel',
} as const;

export const $TokenApiModel = {
  properties: {
    access_token: {
      type: 'string',
      title: 'Access Token',
    },
    token_type: {
      type: 'string',
      title: 'Token Type',
    },
  },
  type: 'object',
  required: ['access_token', 'token_type'],
  title: 'TokenApiModel',
} as const;

export const $UnmarkFundResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'UnmarkFundResponseApiModel',
} as const;

export const $UnpinFundInTableTabBody = {
  properties: {
    fund: {
      type: 'integer',
      title: 'Fund',
    },
  },
  type: 'object',
  required: ['fund'],
  title: 'UnpinFundInTableTabBody',
} as const;

export const $UnpinFundInTableTabResponseApiModel = {
  properties: {
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['success'],
  title: 'UnpinFundInTableTabResponseApiModel',
} as const;

export const $UpdateDashboardFundsBody = {
  properties: {
    fundType: {
      type: 'integer',
      title: 'Fundtype',
    },
    sortParameter: {
      type: 'integer',
      title: 'Sortparameter',
    },
    sortPeriod: {
      type: 'integer',
      title: 'Sortperiod',
    },
  },
  type: 'object',
  required: ['fundType', 'sortParameter', 'sortPeriod'],
  title: 'UpdateDashboardFundsBody',
} as const;

export const $UpdateDashboardFundsResponseApiModel = {
  properties: {
    funds: {
      items: {
        $ref: '#/components/schemas/DashboardFundApiModel',
      },
      type: 'array',
      title: 'Funds',
    },
  },
  type: 'object',
  required: ['funds'],
  title: 'UpdateDashboardFundsResponseApiModel',
} as const;

export const $UpdateFundTabColumnsResponseApiModel = {
  properties: {
    funds: {
      items: {
        $ref: '#/components/schemas/FundsTableItemApiModel',
      },
      type: 'array',
      title: 'Funds',
    },
    columns: {
      items: {
        $ref: '#/components/schemas/FundTableTabColumnDto',
      },
      type: 'array',
      title: 'Columns',
    },
  },
  type: 'object',
  required: ['funds', 'columns'],
  title: 'UpdateFundTabColumnsResponseApiModel',
} as const;

export const $UpdateFundTabSingleColumnResponseApiModel = {
  properties: {
    funds: {
      items: {
        $ref: '#/components/schemas/FundsTableItemApiModel',
      },
      type: 'array',
      title: 'Funds',
    },
    columns: {
      items: {
        $ref: '#/components/schemas/FundTableTabColumnDto',
      },
      type: 'array',
      title: 'Columns',
    },
  },
  type: 'object',
  required: ['funds', 'columns'],
  title: 'UpdateFundTabSingleColumnResponseApiModel',
} as const;

export const $UpdateFundTableTabColumnItem = {
  properties: {
    key: {
      type: 'string',
      title: 'Key',
    },
    sortDirection: {
      $ref: '#/components/schemas/FundTableTabColumnSort',
    },
    visible: {
      type: 'boolean',
      title: 'Visible',
    },
    selectedFilter: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Selectedfilter',
    },
    customPeriodStartJdate: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Customperiodstartjdate',
    },
    customPeriodEndJdate: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Customperiodendjdate',
    },
  },
  type: 'object',
  required: [
    'key',
    'sortDirection',
    'visible',
    'customPeriodStartJdate',
    'customPeriodEndJdate',
  ],
  title: 'UpdateFundTableTabColumnItem',
} as const;

export const $UpdateFundTableTabColumnsBody = {
  properties: {
    columns: {
      items: {
        $ref: '#/components/schemas/UpdateFundTableTabColumnItem',
      },
      type: 'array',
      title: 'Columns',
    },
  },
  type: 'object',
  required: ['columns'],
  title: 'UpdateFundTableTabColumnsBody',
} as const;

export const $UpdateFundTableTabSingleColumnBody = {
  properties: {
    column: {
      $ref: '#/components/schemas/UpdateFundTableTabColumnItem',
    },
  },
  type: 'object',
  required: ['column'],
  title: 'UpdateFundTableTabSingleColumnBody',
} as const;

export const $UserReportFavoriteStatus = {
  properties: {
    userId: {
      type: 'integer',
      title: 'Userid',
    },
    reportId: {
      type: 'integer',
      title: 'Reportid',
    },
    isFavorite: {
      type: 'boolean',
      title: 'Isfavorite',
    },
  },
  type: 'object',
  required: ['userId', 'reportId', 'isFavorite'],
  title: 'UserReportFavoriteStatus',
} as const;

export const $ValidatePasswordForUserBody = {
  properties: {
    password: {
      type: 'string',
      title: 'Password',
    },
  },
  type: 'object',
  required: ['password'],
  title: 'ValidatePasswordForUserBody',
} as const;

export const $ValidatePasswordForUserResponseApiModel = {
  properties: {
    passwordVerificationToken: {
      type: 'string',
      title: 'Passwordverificationtoken',
    },
    success: {
      type: 'boolean',
      title: 'Success',
    },
  },
  type: 'object',
  required: ['passwordVerificationToken', 'success'],
  title: 'ValidatePasswordForUserResponseApiModel',
} as const;

export const $VideoApiModel = {
  properties: {
    identifier: {
      type: 'integer',
      title: 'Identifier',
      description: 'Unique identifier of video',
    },
    title: {
      type: 'string',
      title: 'Title',
      description: 'Title of video',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
      description: 'Description of video',
    },
    mp4Video1080P: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video1080P',
      description: 'Url of mp4 video file in 1080p',
    },
    mp4Video1080PSizeBytes: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video1080Psizebytes',
      description: 'Size of 1080p mp4 video file in bytes',
    },
    mp4Video720P: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video720P',
      description: 'Url of mp4 video file in 720p',
    },
    mp4Video720PSizeBytes: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video720Psizebytes',
      description: 'Size of 720p mp4 video file in bytes',
    },
    mp4Video480P: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video480P',
      description: 'Url of mp4 video file in 480p',
    },
    mp4Video480PSizeBytes: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video480Psizebytes',
      description: 'Size of 480p mp4 video file in bytes',
    },
    mp4Video360P: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video360P',
      description: 'Url of mp4 video file in 360p',
    },
    mp4Video360PSizeBytes: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Mp4Video360Psizebytes',
      description: 'Size of 360p mp4 video file in bytes',
    },
    mp4Video240P: {
      type: 'string',
      title: 'Mp4Video240P',
      description: 'Url of mp4 video file in 240p',
    },
    mp4Video240PSizeBytes: {
      type: 'integer',
      title: 'Mp4Video240Psizebytes',
      description: 'Size of 240p mp4 video file in bytes',
    },
    durationInSeconds: {
      type: 'number',
      title: 'Durationinseconds',
      description: 'Duration of video in seconds',
    },
    poster: {
      type: 'string',
      title: 'Poster',
      description: 'Poster (placeholder) image of video',
    },
    thumbnailImages: {
      items: {
        $ref: '#/components/schemas/VideoThumbnailApiModel',
      },
      type: 'array',
      title: 'Thumbnailimages',
      description: 'Thumbnail of video',
    },
  },
  type: 'object',
  required: [
    'identifier',
    'title',
    'description',
    'mp4Video1080P',
    'mp4Video1080PSizeBytes',
    'mp4Video720P',
    'mp4Video720PSizeBytes',
    'mp4Video480P',
    'mp4Video480PSizeBytes',
    'mp4Video360P',
    'mp4Video360PSizeBytes',
    'mp4Video240P',
    'mp4Video240PSizeBytes',
    'durationInSeconds',
    'poster',
    'thumbnailImages',
  ],
  title: 'VideoApiModel',
} as const;

export const $VideoThumbnailApiModel = {
  properties: {
    startTimeSeconds: {
      type: 'number',
      title: 'Starttimeseconds',
      description: 'From which second we should use this video thumbnail',
    },
    durationSeconds: {
      type: 'number',
      title: 'Durationseconds',
      description:
        'After start time, until how many seconds use this video thumbnail',
    },
    image: {
      type: 'string',
      title: 'Image',
      description: 'Thumbnail file',
    },
    intervalSeconds: {
      type: 'integer',
      title: 'Intervalseconds',
      description: 'Interval in seconds between images',
    },
    widthPixels: {
      type: 'integer',
      title: 'Widthpixels',
      description: 'Width of each thumbnail in pixes',
    },
    heightPixels: {
      type: 'integer',
      title: 'Heightpixels',
      description: 'Height of each thumbnail in pixes',
    },
    columns: {
      type: 'integer',
      title: 'Columns',
      description: 'Number of thumbnails per line',
    },
  },
  type: 'object',
  required: [
    'startTimeSeconds',
    'durationSeconds',
    'image',
    'intervalSeconds',
    'widthPixels',
    'heightPixels',
    'columns',
  ],
  title: 'VideoThumbnailApiModel',
} as const;
