// This file is auto-generated by @hey-api/openapi-ts

export const $AnonymousApiUser = {
    properties: {},
    type: 'object',
    title: 'AnonymousApiUser'
} as const;

export const $AressApiUser = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of user'
        },
        username: {
            type: 'string',
            title: 'Username',
            description: 'Username for the user'
        },
        email: {
            type: 'string',
            title: 'Email',
            description: 'Email for the user.'
        },
        phoneNumber: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phonenumber',
            description: 'Phone number of the user.'
        },
        nationalCode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nationalcode',
            description: 'National code of the user.'
        },
        active: {
            type: 'boolean',
            title: 'Active',
            description: 'Whether this user is active or not, is always "true" for logged in user.'
        }
    },
    type: 'object',
    required: ['identifier', 'username', 'email', 'phoneNumber', 'nationalCode', 'active'],
    title: 'AressApiUser'
} as const;

export const $Body_login_for_access_token_users_login_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_for_access_token_users_login_post'
} as const;

export const $Body_test_user_access_token_users_token_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_test_user_access_token_users_token_post'
} as const;

export const $CaptchaApiModel = {
    properties: {
        value: {
            type: 'string',
            title: 'Value'
        },
        uid: {
            type: 'integer',
            title: 'Uid'
        },
        required: {
            type: 'boolean',
            title: 'Required'
        }
    },
    type: 'object',
    required: ['value', 'uid', 'required'],
    title: 'CaptchaApiModel'
} as const;

export const $CaptchaType = {
    type: 'string',
    enum: ['image', 'audio'],
    title: 'CaptchaType'
} as const;

export const $FinancialReportCategoryApiModel = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of report category'
        }
    },
    type: 'object',
    required: ['title', 'identifier'],
    title: 'FinancialReportCategoryApiModel'
} as const;

export const $FinancialReportDetailsApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of report'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/FinancialReportCategoryApiModel'
        },
        image: {
            type: 'string',
            title: 'Image'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        htmlDescription: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Htmldescription'
        },
        video: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoApiModel'
                },
                {
                    type: 'null'
                }
            ]
        },
        userFavorite: {
            type: 'boolean',
            title: 'Userfavorite',
            default: false
        },
        isNew: {
            type: 'boolean',
            title: 'Isnew',
            default: false
        },
        relatedReports: {
            items: {
                '$ref': '#/components/schemas/FinancialReportListItemApiModel'
            },
            type: 'array',
            title: 'Relatedreports'
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'category', 'image', 'summary', 'htmlDescription', 'video', 'relatedReports'],
    title: 'FinancialReportDetailsApiModel'
} as const;

export const $FinancialReportListItemApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of report'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/FinancialReportCategoryApiModel'
        },
        image: {
            type: 'string',
            title: 'Image'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        video: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoApiModel'
                },
                {
                    type: 'null'
                }
            ]
        },
        userFavorite: {
            type: 'boolean',
            title: 'Userfavorite',
            default: false
        },
        isNew: {
            type: 'boolean',
            title: 'Isnew',
            default: false
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'category', 'image', 'summary', 'video'],
    title: 'FinancialReportListItemApiModel'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $TokenApiModel = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'TokenApiModel'
} as const;

export const $UserReportFavoriteStatus = {
    properties: {
        userId: {
            type: 'integer',
            title: 'Userid'
        },
        reportId: {
            type: 'integer',
            title: 'Reportid'
        },
        isFavorite: {
            type: 'boolean',
            title: 'Isfavorite'
        }
    },
    type: 'object',
    required: ['userId', 'reportId', 'isFavorite'],
    title: 'UserReportFavoriteStatus'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $VideoApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of video'
        },
        mp4Video1080P: {
            type: 'string',
            title: 'Mp4Video1080P',
            description: 'Url of mp4 video file in 1080p'
        },
        mp4Video1080PSizeBytes: {
            type: 'integer',
            title: 'Mp4Video1080Psizebytes',
            description: 'Size of 1080p mp4 video file in bytes'
        },
        mp4Video720P: {
            type: 'string',
            title: 'Mp4Video720P',
            description: 'Url of mp4 video file in 720p'
        },
        mp4Video720PSizeBytes: {
            type: 'integer',
            title: 'Mp4Video720Psizebytes',
            description: 'Size of 720p mp4 video file in bytes'
        },
        mp4Video480P: {
            type: 'string',
            title: 'Mp4Video480P',
            description: 'Url of mp4 video file in 480p'
        },
        mp4Video480PSizeBytes: {
            type: 'integer',
            title: 'Mp4Video480Psizebytes',
            description: 'Size of 480p mp4 video file in bytes'
        },
        mp4Video360P: {
            type: 'string',
            title: 'Mp4Video360P',
            description: 'Url of mp4 video file in 360p'
        },
        mp4Video360PSizeBytes: {
            type: 'integer',
            title: 'Mp4Video360Psizebytes',
            description: 'Size of 360p mp4 video file in bytes'
        },
        mp4Video240P: {
            type: 'string',
            title: 'Mp4Video240P',
            description: 'Url of mp4 video file in 240p'
        },
        mp4Video240PSizeBytes: {
            type: 'integer',
            title: 'Mp4Video240Psizebytes',
            description: 'Size of 240p mp4 video file in bytes'
        },
        durationInSeconds: {
            type: 'number',
            title: 'Durationinseconds',
            description: 'Duration of video in seconds'
        },
        poster1080P: {
            type: 'string',
            title: 'Poster1080P',
            description: 'Poster (placeholder) image of video in medium size (1920x1080)'
        },
        poster720P: {
            type: 'string',
            title: 'Poster720P',
            description: 'Poster (placeholder) image of video in medium size (1280x720)'
        },
        poster480P: {
            type: 'string',
            title: 'Poster480P',
            description: 'Poster (placeholder) image of video in medium size (854x480)'
        },
        poster360P: {
            type: 'string',
            title: 'Poster360P',
            description: 'Poster (placeholder) image of video in medium size (640x360)'
        },
        poster240P: {
            type: 'string',
            title: 'Poster240P',
            description: 'Poster (placeholder) image of video in medium size (426x240)'
        },
        thumbnailImage: {
            type: 'string',
            title: 'Thumbnailimage',
            description: 'Thumbnail of video'
        }
    },
    type: 'object',
    required: ['identifier', 'mp4Video1080P', 'mp4Video1080PSizeBytes', 'mp4Video720P', 'mp4Video720PSizeBytes', 'mp4Video480P', 'mp4Video480PSizeBytes', 'mp4Video360P', 'mp4Video360PSizeBytes', 'mp4Video240P', 'mp4Video240PSizeBytes', 'durationInSeconds', 'poster1080P', 'poster720P', 'poster480P', 'poster360P', 'poster240P', 'thumbnailImage'],
    title: 'VideoApiModel'
} as const;