// This file is auto-generated by @hey-api/openapi-ts

export const $AddReportToDashboardForUserBody = {
    properties: {
        reportIdentifier: {
            type: 'string',
            title: 'Reportidentifier'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        selectedFilters: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selectedfilters'
        }
    },
    type: 'object',
    required: ['reportIdentifier', 'order'],
    title: 'AddReportToDashboardForUserBody'
} as const;

export const $AnonymousApiUser = {
    properties: {},
    type: 'object',
    title: 'AnonymousApiUser'
} as const;

export const $AressApiUser = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of user'
        },
        username: {
            type: 'string',
            title: 'Username',
            description: 'Username for the user'
        },
        email: {
            type: 'string',
            title: 'Email',
            description: 'Email for the user.'
        },
        phoneNumber: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phonenumber',
            description: 'Phone number of the user.'
        },
        nationalCode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nationalcode',
            description: 'National code of the user.'
        },
        active: {
            type: 'boolean',
            title: 'Active',
            description: 'Whether this user is active or not, is always "true" for logged in user.'
        },
        firstName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Firstname',
            description: 'First name of user.'
        },
        lastName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lastname',
            description: 'Last name the user.'
        },
        profilePicture: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profilepicture',
            description: 'Profile picture url of the user.'
        }
    },
    type: 'object',
    required: ['identifier', 'username', 'email', 'phoneNumber', 'nationalCode', 'active', 'firstName', 'lastName', 'profilePicture'],
    title: 'AressApiUser'
} as const;

export const $Body_change_profile_picture_users_profile_picture_change_post = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_change_profile_picture_users_profile_picture_change_post'
} as const;

export const $Body_login_for_access_token_users_login_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_for_access_token_users_login_post'
} as const;

export const $Body_test_user_access_token_users_token_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_test_user_access_token_users_token_post'
} as const;

export const $CaptchaApiModel = {
    properties: {
        value: {
            type: 'string',
            title: 'Value'
        },
        uid: {
            type: 'integer',
            title: 'Uid'
        },
        required: {
            type: 'boolean',
            title: 'Required'
        }
    },
    type: 'object',
    required: ['value', 'uid', 'required'],
    title: 'CaptchaApiModel'
} as const;

export const $CaptchaType = {
    type: 'string',
    enum: ['image', 'audio'],
    title: 'CaptchaType'
} as const;

export const $ChangeDashboardReportItemSortOrderBody = {
    properties: {
        order: {
            type: 'integer',
            title: 'Order'
        }
    },
    type: 'object',
    required: ['order'],
    title: 'ChangeDashboardReportItemSortOrderBody'
} as const;

export const $ChangePasswordByOtpApiModel = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'ChangePasswordByOtpApiModel'
} as const;

export const $ChangePasswordByOtpBody = {
    properties: {
        otp: {
            type: 'string',
            title: 'Otp'
        },
        newPassword: {
            type: 'string',
            title: 'Newpassword'
        }
    },
    type: 'object',
    required: ['otp', 'newPassword'],
    title: 'ChangePasswordByOtpBody'
} as const;

export const $ChangePhoneByOtpBody = {
    properties: {
        otp: {
            type: 'string',
            title: 'Otp'
        }
    },
    type: 'object',
    required: ['otp'],
    title: 'ChangePhoneByOtpBody'
} as const;

export const $ChangePhoneByOtpResponseApiModel = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'ChangePhoneByOtpResponseApiModel'
} as const;

export const $ChangePhoneGetOtpBody = {
    properties: {
        newPhoneNumber: {
            type: 'string',
            title: 'Newphonenumber'
        },
        passwordVerificationToken: {
            type: 'string',
            title: 'Passwordverificationtoken'
        }
    },
    type: 'object',
    required: ['newPhoneNumber', 'passwordVerificationToken'],
    title: 'ChangePhoneGetOtpBody'
} as const;

export const $ChangePhoneGetOtpResponseApiModel = {
    properties: {
        retrySeconds: {
            type: 'integer',
            title: 'Retryseconds'
        },
        phoneNumber: {
            type: 'string',
            title: 'Phonenumber'
        }
    },
    type: 'object',
    required: ['retrySeconds', 'phoneNumber'],
    title: 'ChangePhoneGetOtpResponseApiModel'
} as const;

export const $ChangeProfilePictureResponseApiModel = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'ChangeProfilePictureResponseApiModel'
} as const;

export const $ChangeUsernameBody = {
    properties: {
        newUsername: {
            type: 'string',
            title: 'Newusername'
        },
        passwordVerificationToken: {
            type: 'string',
            title: 'Passwordverificationtoken'
        }
    },
    type: 'object',
    required: ['newUsername', 'passwordVerificationToken'],
    title: 'ChangeUsernameBody'
} as const;

export const $ChangeUsernameResponseApiModel = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'ChangeUsernameResponseApiModel'
} as const;

export const $CreateDashboardForUserBody = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CreateDashboardForUserBody'
} as const;

export const $CreateDashboardResponseApiModel = {
    properties: {
        createdDashboardId: {
            type: 'integer',
            title: 'Createddashboardid'
        },
        dashboards: {
            items: {
                '$ref': '#/components/schemas/DashboardListItemApiModel'
            },
            type: 'array',
            title: 'Dashboards'
        }
    },
    type: 'object',
    required: ['createdDashboardId', 'dashboards'],
    title: 'CreateDashboardResponseApiModel'
} as const;

export const $DashboardDetailsApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/DashboardItemApiModel'
            },
            type: 'array',
            title: 'Items'
        },
        fundsByCategory: {
            items: {
                '$ref': '#/components/schemas/DashboardFundCategoryApiModel'
            },
            type: 'array',
            title: 'Fundsbycategory'
        }
    },
    type: 'object',
    required: ['identifier', 'name', 'items', 'fundsByCategory'],
    title: 'DashboardDetailsApiModel'
} as const;

export const $DashboardFundApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        registrationNumber: {
            type: 'integer',
            title: 'Registrationnumber'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        abbreviatedName: {
            type: 'string',
            title: 'Abbreviatedname'
        },
        returnLastWeekPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastweekpercent'
        },
        returnLastMonthPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastmonthpercent'
        },
        returnLast3MonthsPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlast3Monthspercent'
        },
        returnLastYearPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastyearpercent'
        },
        dailyRedeemNavMonth: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dailyredeemnavmonth'
        }
    },
    type: 'object',
    required: ['identifier', 'registrationNumber', 'name', 'abbreviatedName', 'returnLastWeekPercent', 'returnLastMonthPercent', 'returnLast3MonthsPercent', 'returnLastYearPercent', 'dailyRedeemNavMonth'],
    title: 'DashboardFundApiModel'
} as const;

export const $DashboardFundCategoryApiModel = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of report category'
        },
        funds: {
            items: {
                '$ref': '#/components/schemas/DashboardFundApiModel'
            },
            type: 'array',
            title: 'Funds'
        }
    },
    type: 'object',
    required: ['title', 'identifier', 'funds'],
    title: 'DashboardFundCategoryApiModel'
} as const;

export const $DashboardItemApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        report: {
            '$ref': '#/components/schemas/DashboardItemReportApiModel'
        },
        selectedFilters: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selectedfilters'
        }
    },
    type: 'object',
    required: ['identifier', 'order', 'report', 'selectedFilters'],
    title: 'DashboardItemApiModel'
} as const;

export const $DashboardItemPreviewApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        reportPreview: {
            '$ref': '#/components/schemas/DashboardReportPreviewApiModel'
        }
    },
    type: 'object',
    required: ['identifier', 'order', 'reportPreview'],
    title: 'DashboardItemPreviewApiModel'
} as const;

export const $DashboardItemReportApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of report'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/FinancialReportCategoryApiModel'
        },
        reportCalculation: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FinancialReportCalculationApiModel'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'category', 'reportCalculation'],
    title: 'DashboardItemReportApiModel'
} as const;

export const $DashboardListItemApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['identifier', 'name'],
    title: 'DashboardListItemApiModel'
} as const;

export const $DashboardReportPreviewApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        image: {
            type: 'string',
            title: 'Image'
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'image'],
    title: 'DashboardReportPreviewApiModel'
} as const;

export const $DuplicateDashboardForUserBody = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DuplicateDashboardForUserBody'
} as const;

export const $FinancialReportCalculationApiModel = {
    properties: {
        calculation: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Report2CalculationResult'
                },
                {
                    '$ref': '#/components/schemas/Report6CalculationResult'
                },
                {
                    '$ref': '#/components/schemas/Report13Dot1CalculationResult'
                },
                {
                    '$ref': '#/components/schemas/Report13Dot2CalculationResult'
                },
                {
                    '$ref': '#/components/schemas/Report13Dot3CalculationResult'
                },
                {
                    '$ref': '#/components/schemas/Report15CalculationResult'
                }
            ],
            title: 'Calculation'
        },
        filters: {
            items: {
                '$ref': '#/components/schemas/FinancialReportFilterApiModel'
            },
            type: 'array',
            title: 'Filters'
        }
    },
    type: 'object',
    required: ['calculation', 'filters'],
    title: 'FinancialReportCalculationApiModel'
} as const;

export const $FinancialReportCategoryApiModel = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of report category'
        }
    },
    type: 'object',
    required: ['title', 'identifier'],
    title: 'FinancialReportCategoryApiModel'
} as const;

export const $FinancialReportDetailsApiModel = {
    properties: {
        identifier: {
            type: 'string',
            title: 'Identifier',
            description: 'Unique identifier of report'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/FinancialReportCategoryApiModel'
        },
        image: {
            type: 'string',
            title: 'Image'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        markdownDescription: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Markdowndescription'
        },
        video: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VideoApiModel'
                },
                {
                    type: 'null'
                }
            ]
        },
        userFavorite: {
            type: 'boolean',
            title: 'Userfavorite',
            default: false
        },
        isNew: {
            type: 'boolean',
            title: 'Isnew',
            default: false
        },
        relatedReports: {
            items: {
                '$ref': '#/components/schemas/FinancialReportListItemApiModel'
            },
            type: 'array',
            title: 'Relatedreports'
        },
        reportCalculation: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FinancialReportCalculationApiModel'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'category', 'image', 'summary', 'markdownDescription', 'video', 'relatedReports', 'reportCalculation'],
    title: 'FinancialReportDetailsApiModel'
} as const;

export const $FinancialReportFilterApiModel = {
    properties: {
        parentTitle: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parenttitle'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        searchable: {
            type: 'boolean',
            title: 'Searchable'
        },
        options: {
            items: {
                '$ref': '#/components/schemas/FinancialReportFilterOptionDto'
            },
            type: 'array',
            title: 'Options'
        },
        selectedOption: {
            '$ref': '#/components/schemas/FinancialReportFilterOptionDto'
        },
        optionType: {
            type: 'string',
            title: 'Optiontype'
        }
    },
    type: 'object',
    required: ['parentTitle', 'title', 'searchable', 'options', 'selectedOption', 'optionType'],
    title: 'FinancialReportFilterApiModel'
} as const;

export const $FinancialReportFilterOptionDto = {
    properties: {
        identifier: {
            type: 'string',
            title: 'Identifier'
        },
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['identifier', 'title'],
    title: 'FinancialReportFilterOptionDto'
} as const;

export const $FinancialReportListItemApiModel = {
    properties: {
        identifier: {
            type: 'string',
            title: 'Identifier',
            description: 'Unique identifier of report'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/FinancialReportCategoryApiModel'
        },
        image: {
            type: 'string',
            title: 'Image'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        hasVideo: {
            type: 'boolean',
            title: 'Hasvideo',
            default: false
        },
        userFavorite: {
            type: 'boolean',
            title: 'Userfavorite',
            default: false
        },
        isNew: {
            type: 'boolean',
            title: 'Isnew',
            default: false
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'category', 'image', 'summary'],
    title: 'FinancialReportListItemApiModel'
} as const;

export const $ForgotPasswordResetByOtpBody = {
    properties: {
        otp: {
            type: 'string',
            title: 'Otp'
        },
        newPassword: {
            type: 'string',
            title: 'Newpassword'
        },
        userId: {
            type: 'integer',
            title: 'Userid'
        }
    },
    type: 'object',
    required: ['otp', 'newPassword', 'userId'],
    title: 'ForgotPasswordResetByOtpBody'
} as const;

export const $FundListItemApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'شناسه صندوق'
        },
        registrationNumber: {
            type: 'integer',
            title: 'Registrationnumber',
            description: 'شماره ثبت نزد سازمان بورس'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: 'نام کامل صندوق'
        },
        abbreviatedName: {
            type: 'string',
            title: 'Abbreviatedname',
            description: 'نام صندوق'
        },
        fundType: {
            '$ref': '#/components/schemas/FundTypeApiModel',
            description: 'نوع صندوق'
        },
        logoMedium: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logomedium',
            description: 'آدرس لوگوی صندوق - سایز متوسط'
        },
        logoThumbnail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logothumbnail',
            description: 'آدرس لوگوی صندوق - سایز کوچک'
        },
        website: {
            type: 'string',
            title: 'Website',
            description: 'وبسایت صندوق'
        },
        statuteUrl: {
            type: 'string',
            title: 'Statuteurl',
            description: 'اساسنامه صندوق'
        },
        prospectusUrl: {
            type: 'string',
            title: 'Prospectusurl',
            description: 'امیدنامه صندوق'
        },
        isEtf: {
            type: 'boolean',
            title: 'Isetf',
            description: 'آیا صندوق etf است'
        },
        isCharity: {
            type: 'boolean',
            title: 'Ischarity',
            description: 'آیا صندوق نیکوکاری است'
        },
        hasVideo: {
            type: 'boolean',
            title: 'Hasvideo',
            description: 'دارای ویدیو بررسی'
        },
        manager: {
            type: 'string',
            title: 'Manager',
            description: 'مدیر صنودق'
        },
        custodian: {
            type: 'string',
            title: 'Custodian',
            description: 'متولی صندوق'
        },
        auditor: {
            type: 'string',
            title: 'Auditor',
            description: 'حسابرس صندوق'
        },
        liquidityGuarantor: {
            type: 'string',
            title: 'Liquidityguarantor',
            description: 'ضامن نقد شوندگی صندوق'
        },
        marketMaker: {
            type: 'string',
            title: 'Marketmaker',
            description: 'بازارگردان'
        },
        initiationDate: {
            type: 'string',
            title: 'Initiationdate',
            description: 'تاریخ آغاز فعالیت میلادی'
        },
        initiationJdate: {
            type: 'string',
            title: 'Initiationjdate',
            description: 'تاریخ آغاز فعالیت'
        },
        issueNavRials: {
            type: 'integer',
            title: 'Issuenavrials',
            description: 'قیمت صدور'
        },
        redeemNavRials: {
            type: 'integer',
            title: 'Redeemnavrials',
            description: 'قیمت ابطال'
        },
        statisticalNavRials: {
            type: 'integer',
            title: 'Statisticalnavrials',
            description: 'قیمت آماری'
        },
        assetUnderManagementRials: {
            type: 'integer',
            title: 'Assetundermanagementrials',
            description: 'دارایی تحت مدیریت'
        },
        numberOfUnits: {
            type: 'integer',
            title: 'Numberofunits',
            description: 'تعداد واحد'
        },
        returnLastWeekPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastweekpercent',
            description: 'بازدهی هفته اخیر'
        },
        returnLastMonthPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastmonthpercent',
            description: 'بازدهی ماه اخیر'
        },
        returnLast3MonthsPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlast3Monthspercent',
            description: 'بازدهی سه ماه اخیر'
        },
        returnLastYearPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastyearpercent',
            description: 'بازدهی سال اخیر'
        },
        returnLastWeekVsTedpixPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastweekvstedpixpercent',
            description: 'بازدهی هفته اخیر به شاخص'
        },
        returnLastMonthVsTedpixPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastmonthvstedpixpercent',
            description: 'بازدهی ماه اخیر به شاخص'
        },
        returnLast3MonthsVsTedpixPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlast3Monthsvstedpixpercent',
            description: 'بازدهی سه ماه اخیر به شاخص'
        },
        returnLastYearVsTedpixPercent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Returnlastyearvstedpixpercent',
            description: 'بازدهی سال اخیر به شاخص'
        },
        assetAllocationBondPercent: {
            type: 'number',
            title: 'Assetallocationbondpercent',
            description: 'سهم اوراق از پورتفوی'
        },
        assetAllocationBankDepositPercent: {
            type: 'number',
            title: 'Assetallocationbankdepositpercent',
            description: 'سهم سپرده بانکی از پورتفوی'
        },
        assetAllocationCommodityDepositCertificatePercent: {
            type: 'number',
            title: 'Assetallocationcommoditydepositcertificatepercent',
            description: 'سهم گواهی سپرده کالایی از پورتفوی'
        },
        assetAllocationCashPercent: {
            type: 'number',
            title: 'Assetallocationcashpercent',
            description: 'سهم وجه نقد از پورتفوی'
        },
        assetAllocationStocksIncludingTop5Percent: {
            type: 'number',
            title: 'Assetallocationstocksincludingtop5Percent',
            description: 'سهم سهام از پورتفوی'
        },
        assetAllocationFundUnitsPercent: {
            type: 'number',
            title: 'Assetallocationfundunitspercent',
            description: 'سهم واحد صندوق‌ها از پورتفوی'
        },
        assetAllocationOtherPercent: {
            type: 'number',
            title: 'Assetallocationotherpercent',
            description: 'سهم سایر از پورتفوی'
        },
        assetAllocationTop5StocksPercent: {
            type: 'number',
            title: 'Assetallocationtop5Stockspercent',
            description: 'سهم پنج سهم برتر از پورتفوی'
        },
        averageLeverageLastWeek: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Averageleveragelastweek',
            description: 'میانگین اهرم هفته اخیر'
        },
        averageLeverageLastMonth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Averageleveragelastmonth',
            description: 'میانگین اهرم ماه اخیر'
        },
        averageLeverageLast3Months: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Averageleveragelast3Months',
            description: 'میانگین اهرم سه ماه اخیر'
        },
        averageLeverageLastYear: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Averageleveragelastyear',
            description: 'میانگین اهرم سال اخیر'
        },
        standardDeviationLastWeek: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standarddeviationlastweek',
            description: 'انحراف از میانگین هفته اخیر'
        },
        standardDeviationLastMonth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standarddeviationlastmonth',
            description: 'انحراف از میانگین ماه اخیر'
        },
        standardDeviationLast3Month: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standarddeviationlast3Month',
            description: 'انحراف از میانگین سه ماه اخیر'
        },
        standardDeviationLastYear: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Standarddeviationlastyear',
            description: 'انحراف از میانگین سال اخیر'
        },
        sharpeRatioLastWeek: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharperatiolastweek',
            description: 'نسبت شارپی هفته اخیر'
        },
        sharpeRatioLastMonth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharperatiolastmonth',
            description: 'نسبت شارپی ماه اخیر'
        },
        sharpeRatioLast3Months: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharperatiolast3Months',
            description: 'نسبت شارپی سه ماه اخیر'
        },
        sharpeRatioLastYear: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharperatiolastyear',
            description: 'نسبت شارپی سال اخیر'
        },
        informationRatioLastWeek: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Informationratiolastweek',
            description: 'نسبت اصلاعاتی هفته اخیر'
        },
        informationRatioLastMonth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Informationratiolastmonth',
            description: 'نسبت اصلاعاتی ماه اخیر'
        },
        informationRatioLast3Months: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Informationratiolast3Months',
            description: 'نسبت اصلاعاتی سه ماه اخیر'
        },
        informationRatioLastYear: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Informationratiolastyear',
            description: 'نسبت اصلاعاتی سال اخیر'
        },
        alphaLastDay: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alphalastday',
            description: 'آلفا روز اخیر'
        },
        alphaLastWeek: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alphalastweek',
            description: 'آلفا هفته اخیر'
        },
        alphaLastMonth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alphalastmonth',
            description: 'آلفا ماه اخیر'
        },
        alphaLast3Months: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alphalast3Months',
            description: 'آلفا سه ماه اخیر'
        },
        alphaLastYear: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alphalastyear',
            description: 'آلفا سال اخیر'
        },
        betaLastDay: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Betalastday',
            description: 'بتا روز اخیر'
        },
        betaLastWeek: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Betalastweek',
            description: 'بتا هفته اخیر'
        },
        betaLastMonth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Betalastmonth',
            description: 'بتا ماه اخیر'
        },
        betaLast3Months: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Betalast3Months',
            description: 'بتا سه ماه اخیر'
        },
        betaLastYear: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Betalastyear',
            description: 'بتا سال اخیر'
        },
        maxDrawdownWeek: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdrawdownweek',
            description: 'ماکزیمم افت هفته اخیر'
        },
        maxDrawdownMonth: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdrawdownmonth',
            description: 'ماکزیمم افت ماه اخیر'
        },
        maxDrawdown3Month: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdrawdown3Month',
            description: 'ماکزیمم افت سه ماه اخیر'
        },
        maxDrawdownYear: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maxdrawdownyear',
            description: 'ماکزیمم افت سال اخیر'
        },
        dailyRedeemNavMonth: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dailyredeemnavmonth',
            description: 'قیمت ابطال روزانه ماه اخیر'
        }
    },
    type: 'object',
    required: ['identifier', 'registrationNumber', 'name', 'abbreviatedName', 'fundType', 'logoMedium', 'logoThumbnail', 'website', 'statuteUrl', 'prospectusUrl', 'isEtf', 'isCharity', 'hasVideo', 'manager', 'custodian', 'auditor', 'liquidityGuarantor', 'marketMaker', 'initiationDate', 'initiationJdate', 'issueNavRials', 'redeemNavRials', 'statisticalNavRials', 'assetUnderManagementRials', 'numberOfUnits', 'returnLastWeekPercent', 'returnLastMonthPercent', 'returnLast3MonthsPercent', 'returnLastYearPercent', 'returnLastWeekVsTedpixPercent', 'returnLastMonthVsTedpixPercent', 'returnLast3MonthsVsTedpixPercent', 'returnLastYearVsTedpixPercent', 'assetAllocationBondPercent', 'assetAllocationBankDepositPercent', 'assetAllocationCommodityDepositCertificatePercent', 'assetAllocationCashPercent', 'assetAllocationStocksIncludingTop5Percent', 'assetAllocationFundUnitsPercent', 'assetAllocationOtherPercent', 'assetAllocationTop5StocksPercent', 'averageLeverageLastWeek', 'averageLeverageLastMonth', 'averageLeverageLast3Months', 'averageLeverageLastYear', 'standardDeviationLastWeek', 'standardDeviationLastMonth', 'standardDeviationLast3Month', 'standardDeviationLastYear', 'sharpeRatioLastWeek', 'sharpeRatioLastMonth', 'sharpeRatioLast3Months', 'sharpeRatioLastYear', 'informationRatioLastWeek', 'informationRatioLastMonth', 'informationRatioLast3Months', 'informationRatioLastYear', 'alphaLastDay', 'alphaLastWeek', 'alphaLastMonth', 'alphaLast3Months', 'alphaLastYear', 'betaLastDay', 'betaLastWeek', 'betaLastMonth', 'betaLast3Months', 'betaLastYear', 'maxDrawdownWeek', 'maxDrawdownMonth', 'maxDrawdown3Month', 'maxDrawdownYear', 'dailyRedeemNavMonth'],
    title: 'FundListItemApiModel'
} as const;

export const $FundTableResponseApiModel = {
    properties: {
        tabs: {
            items: {
                '$ref': '#/components/schemas/FundTableTabApiModel'
            },
            type: 'array',
            title: 'Tabs'
        },
        selectedTabIdentifier: {
            type: 'integer',
            title: 'Selectedtabidentifier'
        },
        selectedTabFunds: {
            items: {
                '$ref': '#/components/schemas/FundsTableItemApiModel'
            },
            type: 'array',
            title: 'Selectedtabfunds'
        }
    },
    type: 'object',
    required: ['tabs', 'selectedTabIdentifier', 'selectedTabFunds'],
    title: 'FundTableResponseApiModel'
} as const;

export const $FundTableTabApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'color'],
    title: 'FundTableTabApiModel'
} as const;

export const $FundTypeApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier'
        },
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['identifier', 'title'],
    title: 'FundTypeApiModel'
} as const;

export const $FundsTableItemApiModel = {
    properties: {
        fund: {
            '$ref': '#/components/schemas/FundListItemApiModel'
        },
        pinned: {
            type: 'boolean',
            title: 'Pinned'
        }
    },
    type: 'object',
    required: ['fund', 'pinned'],
    title: 'FundsTableItemApiModel'
} as const;

export const $GetDashboardItemCalculationsBody = {
    properties: {
        selectedFilters: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selectedfilters'
        }
    },
    type: 'object',
    title: 'GetDashboardItemCalculationsBody'
} as const;

export const $GetForgotPasswordOtpBody = {
    properties: {
        nationalCode: {
            type: 'string',
            title: 'Nationalcode'
        },
        phoneNumber: {
            type: 'string',
            title: 'Phonenumber'
        },
        captchaUid: {
            type: 'integer',
            title: 'Captchauid'
        },
        captchaValue: {
            type: 'string',
            title: 'Captchavalue'
        }
    },
    type: 'object',
    required: ['nationalCode', 'phoneNumber', 'captchaUid', 'captchaValue'],
    title: 'GetForgotPasswordOtpBody'
} as const;

export const $GetOtpForChangePasswordResponseApiModel = {
    properties: {
        retrySeconds: {
            type: 'integer',
            title: 'Retryseconds'
        },
        phoneNumber: {
            type: 'string',
            title: 'Phonenumber'
        },
        userId: {
            type: 'integer',
            title: 'Userid'
        }
    },
    type: 'object',
    required: ['retrySeconds', 'phoneNumber', 'userId'],
    title: 'GetOtpForChangePasswordResponseApiModel'
} as const;

export const $GetOtpForForgotPasswordResponseApiModel = {
    properties: {
        retrySeconds: {
            type: 'integer',
            title: 'Retryseconds'
        },
        phoneNumber: {
            type: 'string',
            title: 'Phonenumber'
        },
        userId: {
            type: 'integer',
            title: 'Userid'
        }
    },
    type: 'object',
    required: ['retrySeconds', 'phoneNumber', 'userId'],
    title: 'GetOtpForForgotPasswordResponseApiModel'
} as const;

export const $GetReportCalculationsBody = {
    properties: {
        selectedFilters: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Selectedfilters'
        }
    },
    type: 'object',
    required: ['selectedFilters'],
    title: 'GetReportCalculationsBody'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $HealthApiModel = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'HealthApiModel'
} as const;

export const $PinFundInTableTabBody = {
    properties: {
        tab: {
            type: 'integer',
            title: 'Tab'
        },
        fund: {
            type: 'integer',
            title: 'Fund'
        }
    },
    type: 'object',
    required: ['tab', 'fund'],
    title: 'PinFundInTableTabBody'
} as const;

export const $PinFundInTableTabResponseApiModel = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'PinFundInTableTabResponseApiModel'
} as const;

export const $RenameDashboardForUserBody = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RenameDashboardForUserBody'
} as const;

export const $Report13Dot1CalculationResult = {
    properties: {
        lastDay: {
            '$ref': '#/components/schemas/Report13Dot1CalculationResultColumn'
        },
        lastDayNormalized: {
            '$ref': '#/components/schemas/Report13Dot1CalculationResultColumnNormalized'
        },
        maxValue: {
            '$ref': '#/components/schemas/Report13Dot1CalculationResultColumn'
        },
        minValue: {
            '$ref': '#/components/schemas/Report13Dot1CalculationResultColumn'
        },
        averageValue: {
            '$ref': '#/components/schemas/Report13Dot1CalculationResultColumn'
        }
    },
    type: 'object',
    required: ['lastDay', 'lastDayNormalized', 'maxValue', 'minValue', 'averageValue'],
    title: 'Report13Dot1CalculationResult'
} as const;

export const $Report13Dot1CalculationResultColumn = {
    properties: {
        totalTrades: {
            type: 'number',
            title: 'Totaltrades'
        },
        totalBuyIndividual: {
            type: 'number',
            title: 'Totalbuyindividual'
        },
        totalBuyCorporate: {
            type: 'number',
            title: 'Totalbuycorporate'
        },
        totalSellIndividual: {
            type: 'number',
            title: 'Totalsellindividual'
        },
        totalSellCorporate: {
            type: 'number',
            title: 'Totalsellcorporate'
        }
    },
    type: 'object',
    required: ['totalTrades', 'totalBuyIndividual', 'totalBuyCorporate', 'totalSellIndividual', 'totalSellCorporate'],
    title: 'Report13Dot1CalculationResultColumn'
} as const;

export const $Report13Dot1CalculationResultColumnNormalized = {
    properties: {
        totalTradesNormalized: {
            type: 'number',
            title: 'Totaltradesnormalized'
        },
        totalBuyIndividualNormalized: {
            type: 'number',
            title: 'Totalbuyindividualnormalized'
        },
        totalBuyCorporateNormalized: {
            type: 'number',
            title: 'Totalbuycorporatenormalized'
        },
        totalSellIndividualNormalized: {
            type: 'number',
            title: 'Totalsellindividualnormalized'
        },
        totalSellCorporateNormalized: {
            type: 'number',
            title: 'Totalsellcorporatenormalized'
        }
    },
    type: 'object',
    required: ['totalTradesNormalized', 'totalBuyIndividualNormalized', 'totalBuyCorporateNormalized', 'totalSellIndividualNormalized', 'totalSellCorporateNormalized'],
    title: 'Report13Dot1CalculationResultColumnNormalized'
} as const;

export const $Report13Dot2CalculationResult = {
    properties: {
        data: {
            '$ref': '#/components/schemas/Report13Dot2CalculationResultItem'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'Report13Dot2CalculationResult'
} as const;

export const $Report13Dot2CalculationResultItem = {
    properties: {
        mean: {
            type: 'number',
            title: 'Mean'
        },
        median: {
            type: 'number',
            title: 'Median'
        },
        lastTrade: {
            type: 'number',
            title: 'Lasttrade'
        },
        kdePoints: {
            items: {
                '$ref': '#/components/schemas/Report13Dot2GraphKdeResultItem'
            },
            type: 'array',
            title: 'Kdepoints'
        },
        histPoints: {
            items: {
                '$ref': '#/components/schemas/Report13Dot2GraphHistResultItem'
            },
            type: 'array',
            title: 'Histpoints'
        }
    },
    type: 'object',
    required: ['mean', 'median', 'lastTrade', 'kdePoints', 'histPoints'],
    title: 'Report13Dot2CalculationResultItem'
} as const;

export const $Report13Dot2GraphHistResultItem = {
    properties: {
        xMin: {
            type: 'number',
            title: 'Xmin'
        },
        xMax: {
            type: 'number',
            title: 'Xmax'
        },
        y: {
            type: 'number',
            title: 'Y'
        }
    },
    type: 'object',
    required: ['xMin', 'xMax', 'y'],
    title: 'Report13Dot2GraphHistResultItem'
} as const;

export const $Report13Dot2GraphKdeResultItem = {
    properties: {
        x: {
            type: 'number',
            title: 'X'
        },
        y: {
            type: 'number',
            title: 'Y'
        }
    },
    type: 'object',
    required: ['x', 'y'],
    title: 'Report13Dot2GraphKdeResultItem'
} as const;

export const $Report13Dot3CalculationResult = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/Report13Dot3CalculationResultItem'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'Report13Dot3CalculationResult'
} as const;

export const $Report13Dot3CalculationResultItem = {
    properties: {
        points: {
            items: {
                '$ref': '#/components/schemas/Report13Dot3CalculationResultPoints'
            },
            type: 'array',
            title: 'Points'
        },
        mean: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Mean'
        }
    },
    type: 'object',
    required: ['points', 'mean'],
    title: 'Report13Dot3CalculationResultItem'
} as const;

export const $Report13Dot3CalculationResultPoints = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        value: {
            type: 'integer',
            title: 'Value'
        }
    },
    type: 'object',
    required: ['date', 'value'],
    title: 'Report13Dot3CalculationResultPoints'
} as const;

export const $Report15CalculationResult = {
    properties: {
        beta: {
            type: 'number',
            title: 'Beta'
        },
        betaAdjusted: {
            type: 'number',
            title: 'Betaadjusted'
        },
        yIntersect: {
            type: 'number',
            title: 'Yintersect'
        },
        rSquared: {
            type: 'number',
            title: 'Rsquared'
        },
        pValue: {
            type: 'number',
            title: 'Pvalue'
        },
        graphData: {
            items: {
                '$ref': '#/components/schemas/Report15CalculationResultGraphPoint'
            },
            type: 'array',
            title: 'Graphdata'
        }
    },
    type: 'object',
    required: ['beta', 'betaAdjusted', 'yIntersect', 'rSquared', 'pValue', 'graphData'],
    title: 'Report15CalculationResult'
} as const;

export const $Report15CalculationResultGraphPoint = {
    properties: {
        x: {
            type: 'number',
            title: 'X'
        },
        y: {
            type: 'number',
            title: 'Y'
        }
    },
    type: 'object',
    required: ['x', 'y'],
    title: 'Report15CalculationResultGraphPoint'
} as const;

export const $Report2CalculationResult = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/Report2CalculationResultItem'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'Report2CalculationResult'
} as const;

export const $Report2CalculationResultItem = {
    properties: {
        sectorTitle: {
            type: 'string',
            title: 'Sectortitle'
        },
        netFlow: {
            type: 'integer',
            title: 'Netflow'
        }
    },
    type: 'object',
    required: ['sectorTitle', 'netFlow'],
    title: 'Report2CalculationResultItem'
} as const;

export const $Report6CalculationResult = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/Report6CalculationResultTimeSeriesItem'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'Report6CalculationResult'
} as const;

export const $Report6CalculationResultTimeSeriesItem = {
    properties: {
        dt: {
            type: 'string',
            format: 'date',
            title: 'Dt'
        },
        indexValue: {
            type: 'number',
            title: 'Indexvalue'
        },
        netFlow: {
            type: 'integer',
            title: 'Netflow'
        }
    },
    type: 'object',
    required: ['dt', 'indexValue', 'netFlow'],
    title: 'Report6CalculationResultTimeSeriesItem'
} as const;

export const $ResetForgotPasswordByOtpResponseApiModel = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'ResetForgotPasswordByOtpResponseApiModel'
} as const;

export const $TokenApiModel = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'TokenApiModel'
} as const;

export const $UnpinFundInTableTabBody = {
    properties: {
        tab: {
            type: 'integer',
            title: 'Tab'
        },
        fund: {
            type: 'integer',
            title: 'Fund'
        }
    },
    type: 'object',
    required: ['tab', 'fund'],
    title: 'UnpinFundInTableTabBody'
} as const;

export const $UnpinFundInTableTabResponseApiModel = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'UnpinFundInTableTabResponseApiModel'
} as const;

export const $UserReportFavoriteStatus = {
    properties: {
        userId: {
            type: 'integer',
            title: 'Userid'
        },
        reportId: {
            type: 'integer',
            title: 'Reportid'
        },
        isFavorite: {
            type: 'boolean',
            title: 'Isfavorite'
        }
    },
    type: 'object',
    required: ['userId', 'reportId', 'isFavorite'],
    title: 'UserReportFavoriteStatus'
} as const;

export const $ValidatePasswordForUserBody = {
    properties: {
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['password'],
    title: 'ValidatePasswordForUserBody'
} as const;

export const $ValidatePasswordForUserResponseApiModel = {
    properties: {
        passwordVerificationToken: {
            type: 'string',
            title: 'Passwordverificationtoken'
        },
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['passwordVerificationToken', 'success'],
    title: 'ValidatePasswordForUserResponseApiModel'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $VideoApiModel = {
    properties: {
        identifier: {
            type: 'integer',
            title: 'Identifier',
            description: 'Unique identifier of video'
        },
        title: {
            type: 'string',
            title: 'Title',
            description: 'Title of video'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Description of video'
        },
        mp4Video1080P: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video1080P',
            description: 'Url of mp4 video file in 1080p'
        },
        mp4Video1080PSizeBytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video1080Psizebytes',
            description: 'Size of 1080p mp4 video file in bytes'
        },
        mp4Video720P: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video720P',
            description: 'Url of mp4 video file in 720p'
        },
        mp4Video720PSizeBytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video720Psizebytes',
            description: 'Size of 720p mp4 video file in bytes'
        },
        mp4Video480P: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video480P',
            description: 'Url of mp4 video file in 480p'
        },
        mp4Video480PSizeBytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video480Psizebytes',
            description: 'Size of 480p mp4 video file in bytes'
        },
        mp4Video360P: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video360P',
            description: 'Url of mp4 video file in 360p'
        },
        mp4Video360PSizeBytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mp4Video360Psizebytes',
            description: 'Size of 360p mp4 video file in bytes'
        },
        mp4Video240P: {
            type: 'string',
            title: 'Mp4Video240P',
            description: 'Url of mp4 video file in 240p'
        },
        mp4Video240PSizeBytes: {
            type: 'integer',
            title: 'Mp4Video240Psizebytes',
            description: 'Size of 240p mp4 video file in bytes'
        },
        durationInSeconds: {
            type: 'number',
            title: 'Durationinseconds',
            description: 'Duration of video in seconds'
        },
        poster: {
            type: 'string',
            title: 'Poster',
            description: 'Poster (placeholder) image of video'
        },
        thumbnailImages: {
            items: {
                '$ref': '#/components/schemas/VideoThumbnailApiModel'
            },
            type: 'array',
            title: 'Thumbnailimages',
            description: 'Thumbnail of video'
        }
    },
    type: 'object',
    required: ['identifier', 'title', 'description', 'mp4Video1080P', 'mp4Video1080PSizeBytes', 'mp4Video720P', 'mp4Video720PSizeBytes', 'mp4Video480P', 'mp4Video480PSizeBytes', 'mp4Video360P', 'mp4Video360PSizeBytes', 'mp4Video240P', 'mp4Video240PSizeBytes', 'durationInSeconds', 'poster', 'thumbnailImages'],
    title: 'VideoApiModel'
} as const;

export const $VideoThumbnailApiModel = {
    properties: {
        startTimeSeconds: {
            type: 'number',
            title: 'Starttimeseconds',
            description: 'From which second we should use this video thumbnail'
        },
        durationSeconds: {
            type: 'number',
            title: 'Durationseconds',
            description: 'After start time, until how many seconds use this video thumbnail'
        },
        image: {
            type: 'string',
            title: 'Image',
            description: 'Thumbnail file'
        },
        intervalSeconds: {
            type: 'integer',
            title: 'Intervalseconds',
            description: 'Interval in seconds between images'
        },
        widthPixels: {
            type: 'integer',
            title: 'Widthpixels',
            description: 'Width of each thumbnail in pixes'
        },
        heightPixels: {
            type: 'integer',
            title: 'Heightpixels',
            description: 'Height of each thumbnail in pixes'
        },
        columns: {
            type: 'integer',
            title: 'Columns',
            description: 'Number of thumbnails per line'
        }
    },
    type: 'object',
    required: ['startTimeSeconds', 'durationSeconds', 'image', 'intervalSeconds', 'widthPixels', 'heightPixels', 'columns'],
    title: 'VideoThumbnailApiModel'
} as const;