// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUsersLoginCaptchaData, GetUsersLoginCaptchaResponse, PostUsersLoginData, PostUsersLoginResponse, PostUsersTokenData, PostUsersTokenResponse, GetUsersMeResponse, GetDashboardReportsData, GetDashboardReportsResponse, GetDashboardReportsByReportIdData, GetDashboardReportsByReportIdResponse, GetDashboardReportsCategoriesResponse, PostDashboardReportsByReportIdFavoriteData, PostDashboardReportsByReportIdFavoriteResponse, DeleteDashboardReportsByReportIdFavoriteData, DeleteDashboardReportsByReportIdFavoriteResponse } from './types.gen';

export class UsersService {
    /**
     * Captcha For Login
     * Get captcha for a user. Captcha can be an **image** or an **audio**, depending on the **captchaType** param. In case of an image, you can also pass **captchaWidth** and **captchaHeight** for customizing the size of generated image.
     * @param data The data for the request.
     * @param data.captchaWidth
     * @param data.captchaHeight
     * @param data.captchaType
     * @returns CaptchaApiModel Successful Response
     * @throws ApiError
     */
    public static getUsersLoginCaptcha(data: GetUsersLoginCaptchaData = {}): CancelablePromise<GetUsersLoginCaptchaResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/users/login_captcha',
            query: {
                captchaWidth: data.captchaWidth,
                captchaHeight: data.captchaHeight,
                captchaType: data.captchaType
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Login For Access Token
     * Get access token using credentials for users. You must provide solved captcha value (_captcha_) and unique identifier of catpcha (_captchaUid_), along with user credentials (_username_ and _password_).**Important note**: _username_ can be either username, email, phone number or national code of user.
     * @param data The data for the request.
     * @param data.captchaUid
     * @param data.captcha
     * @param data.formData
     * @returns TokenApiModel Successful Response
     * @throws ApiError
     */
    public static postUsersLogin(data: PostUsersLoginData): CancelablePromise<PostUsersLoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/users/login',
            query: {
                captchaUid: data.captchaUid,
                captcha: data.captcha
            },
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test User Access Token
     * Get access token using credentials for test user. This method only works for **test** user. For login flow of real users, you must use **login_captcha** and **login** endpoints.
     * @param data The data for the request.
     * @param data.formData
     * @returns TokenApiModel Successful Response
     * @throws ApiError
     */
    public static postUsersToken(data: PostUsersTokenData): CancelablePromise<PostUsersTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/users/token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Current User
     * Get data of current logged in user.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getUsersMe(): CancelablePromise<GetUsersMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/users/me'
        });
    }
    
}

export class DashboardService {
    /**
     * Report List
     * Get list of reports.
     * @param data The data for the request.
     * @param data.onlyFavorite
     * @param data.onlyNew
     * @param data.onlyHavingVideo
     * @returns FinancialReportListItemApiModel Successful Response
     * @throws ApiError
     */
    public static getDashboardReports(data: GetDashboardReportsData = {}): CancelablePromise<GetDashboardReportsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/dashboard/reports',
            query: {
                onlyFavorite: data.onlyFavorite,
                onlyNew: data.onlyNew,
                onlyHavingVideo: data.onlyHavingVideo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Report Details
     * Get list of reports.
     * @param data The data for the request.
     * @param data.reportId
     * @returns FinancialReportDetailsApiModel Successful Response
     * @throws ApiError
     */
    public static getDashboardReportsByReportId(data: GetDashboardReportsByReportIdData): CancelablePromise<GetDashboardReportsByReportIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/dashboard/reports/{report_id}',
            path: {
                report_id: data.reportId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Report Categories
     * Get list of report categories.
     * @returns FinancialReportCategoryApiModel Successful Response
     * @throws ApiError
     */
    public static getDashboardReportsCategories(): CancelablePromise<GetDashboardReportsCategoriesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/dashboard/reports/categories'
        });
    }
    
    /**
     * Add Report To Favorites
     * Add a report to favorites
     * @param data The data for the request.
     * @param data.reportId
     * @returns UserReportFavoriteStatus Successful Response
     * @throws ApiError
     */
    public static postDashboardReportsByReportIdFavorite(data: PostDashboardReportsByReportIdFavoriteData): CancelablePromise<PostDashboardReportsByReportIdFavoriteResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/dashboard/reports/{report_id}/favorite',
            path: {
                report_id: data.reportId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Remove Report From Favorites
     * Remove a report from favorites
     * @param data The data for the request.
     * @param data.reportId
     * @returns UserReportFavoriteStatus Successful Response
     * @throws ApiError
     */
    public static deleteDashboardReportsByReportIdFavorite(data: DeleteDashboardReportsByReportIdFavoriteData): CancelablePromise<DeleteDashboardReportsByReportIdFavoriteResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/dashboard/reports/{report_id}/favorite',
            path: {
                report_id: data.reportId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}