// This file is auto-generated by @hey-api/openapi-ts

export type AnonymousApiUser = {
    [key: string]: unknown;
};

export type AressApiUser = {
    /**
     * Unique identifier of user
     */
    identifier: number;
    /**
     * Username for the user
     */
    username: string;
    /**
     * Email for the user.
     */
    email: string;
    /**
     * Phone number of the user.
     */
    phoneNumber: string | null;
    /**
     * National code of the user.
     */
    nationalCode: string | null;
    /**
     * Whether this user is active or not, is always "true" for logged in user.
     */
    active: boolean;
};

export type Body_login_for_access_token_users_login_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_test_user_access_token_users_token_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CaptchaApiModel = {
    value: string;
    uid: number;
    required: boolean;
};

export type CaptchaType = 'image' | 'audio';

export type FinancialReportCategoryApiModel = {
    title: string;
    /**
     * Unique identifier of report category
     */
    identifier: number;
};

export type FinancialReportDetailsApiModel = {
    /**
     * Unique identifier of report
     */
    identifier: number;
    title: string;
    category: FinancialReportCategoryApiModel;
    image: string;
    summary: string;
    htmlDescription: string | null;
    video: VideoApiModel | null;
    userFavorite?: boolean;
    isNew?: boolean;
    relatedReports: Array<FinancialReportListItemApiModel>;
};

export type FinancialReportListItemApiModel = {
    /**
     * Unique identifier of report
     */
    identifier: number;
    title: string;
    category: FinancialReportCategoryApiModel;
    image: string;
    summary: string;
    video: VideoApiModel | null;
    userFavorite?: boolean;
    isNew?: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type TokenApiModel = {
    access_token: string;
    token_type: string;
};

export type UserReportFavoriteStatus = {
    userId: number;
    reportId: number;
    isFavorite: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VideoApiModel = {
    /**
     * Unique identifier of video
     */
    identifier: number;
    /**
     * Url of mp4 video file in 1080p
     */
    mp4Video1080P: string;
    /**
     * Size of 1080p mp4 video file in bytes
     */
    mp4Video1080PSizeBytes: number;
    /**
     * Url of mp4 video file in 720p
     */
    mp4Video720P: string;
    /**
     * Size of 720p mp4 video file in bytes
     */
    mp4Video720PSizeBytes: number;
    /**
     * Url of mp4 video file in 480p
     */
    mp4Video480P: string;
    /**
     * Size of 480p mp4 video file in bytes
     */
    mp4Video480PSizeBytes: number;
    /**
     * Url of mp4 video file in 360p
     */
    mp4Video360P: string;
    /**
     * Size of 360p mp4 video file in bytes
     */
    mp4Video360PSizeBytes: number;
    /**
     * Url of mp4 video file in 240p
     */
    mp4Video240P: string;
    /**
     * Size of 240p mp4 video file in bytes
     */
    mp4Video240PSizeBytes: number;
    /**
     * Duration of video in seconds
     */
    durationInSeconds: number;
    /**
     * Poster (placeholder) image of video in medium size (1920x1080)
     */
    poster1080P: string;
    /**
     * Poster (placeholder) image of video in medium size (1280x720)
     */
    poster720P: string;
    /**
     * Poster (placeholder) image of video in medium size (854x480)
     */
    poster480P: string;
    /**
     * Poster (placeholder) image of video in medium size (640x360)
     */
    poster360P: string;
    /**
     * Poster (placeholder) image of video in medium size (426x240)
     */
    poster240P: string;
    /**
     * Thumbnail of video
     */
    thumbnailImage: string;
};

export type GetUsersLoginCaptchaData = {
    captchaHeight?: number;
    captchaType?: CaptchaType;
    captchaWidth?: number;
};

export type GetUsersLoginCaptchaResponse = CaptchaApiModel;

export type PostUsersLoginData = {
    captcha: string | null;
    captchaUid: number | null;
    formData: Body_login_for_access_token_users_login_post;
};

export type PostUsersLoginResponse = TokenApiModel;

export type PostUsersTokenData = {
    formData: Body_test_user_access_token_users_token_post;
};

export type PostUsersTokenResponse = TokenApiModel;

export type GetUsersMeResponse = AressApiUser | AnonymousApiUser;

export type GetDashboardReportsData = {
    onlyFavorite?: boolean | null;
    onlyHavingVideo?: boolean | null;
    onlyNew?: boolean | null;
};

export type GetDashboardReportsResponse = Array<FinancialReportListItemApiModel>;

export type GetDashboardReportsByReportIdData = {
    reportId: number;
};

export type GetDashboardReportsByReportIdResponse = FinancialReportDetailsApiModel;

export type GetDashboardReportsCategoriesResponse = Array<FinancialReportCategoryApiModel>;

export type PostDashboardReportsByReportIdFavoriteData = {
    reportId: number;
};

export type PostDashboardReportsByReportIdFavoriteResponse = UserReportFavoriteStatus;

export type DeleteDashboardReportsByReportIdFavoriteData = {
    reportId: number;
};

export type DeleteDashboardReportsByReportIdFavoriteResponse = UserReportFavoriteStatus;

export type $OpenApiTs = {
    '/users/login_captcha': {
        get: {
            req: GetUsersLoginCaptchaData;
            res: {
                /**
                 * Successful Response
                 */
                200: CaptchaApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/login': {
        post: {
            req: PostUsersLoginData;
            res: {
                /**
                 * Successful Response
                 */
                200: TokenApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/token': {
        post: {
            req: PostUsersTokenData;
            res: {
                /**
                 * Successful Response
                 */
                200: TokenApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: AressApiUser | AnonymousApiUser;
            };
        };
    };
    '/dashboard/reports': {
        get: {
            req: GetDashboardReportsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<FinancialReportListItemApiModel>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/dashboard/reports/{report_id}': {
        get: {
            req: GetDashboardReportsByReportIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: FinancialReportDetailsApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/dashboard/reports/categories': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<FinancialReportCategoryApiModel>;
            };
        };
    };
    '/dashboard/reports/{report_id}/favorite': {
        post: {
            req: PostDashboardReportsByReportIdFavoriteData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserReportFavoriteStatus;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteDashboardReportsByReportIdFavoriteData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserReportFavoriteStatus;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};