// This file is auto-generated by @hey-api/openapi-ts

export type AddReportToDashboardForUserBody = {
    reportIdentifier: string;
    order: number;
    selectedFilters?: {
    [key: string]: unknown;
} | null;
};

export type AnonymousApiUser = {
    [key: string]: unknown;
};

export type AressApiUser = {
    /**
     * Unique identifier of user
     */
    identifier: number;
    /**
     * Username for the user
     */
    username: string;
    /**
     * Email for the user.
     */
    email: string;
    /**
     * Phone number of the user.
     */
    phoneNumber: string | null;
    /**
     * National code of the user.
     */
    nationalCode: string | null;
    /**
     * Whether this user is active or not, is always "true" for logged in user.
     */
    active: boolean;
};

export type Body_change_profile_picture_users_profile_picture_change_post = {
    file: (Blob | File);
};

export type Body_login_for_access_token_users_login_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_test_user_access_token_users_token_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CaptchaApiModel = {
    value: string;
    uid: number;
    required: boolean;
};

export type CaptchaType = 'image' | 'audio';

export type ChangeDashboardReportItemSortOrderBody = {
    dashboardItemId: number;
    order: number;
};

export type ChangePasswordByOtpApiModel = {
    success: boolean;
};

export type ChangePasswordByOtpBody = {
    otp: string;
    newPassword: string;
};

export type ChangePhoneByOtpBody = {
    otp: string;
};

export type ChangePhoneByOtpResponseApiModel = {
    success: boolean;
};

export type ChangePhoneGetOtpBody = {
    newPhoneNumber: string;
    passwordVerificationToken: string;
};

export type ChangePhoneGetOtpResponseApiModel = {
    retrySeconds: number;
    phoneNumber: string;
};

export type ChangeProfilePictureResponseApiModel = {
    success: boolean;
};

export type ChangeUsernameBody = {
    newUsername: string;
    passwordVerificationToken: string;
};

export type ChangeUsernameResponseApiModel = {
    success: boolean;
};

export type CreateDashboardForUserBody = {
    name: string;
};

export type DashboardDetailsApiModel = {
    identifier: number;
    name: string;
    reports: Array<DashboardItemApiModel>;
    fundsByCategory: Array<DashboardFundCategoryApiModel>;
};

export type DashboardFundApiModel = {
    identifier: number;
    registrationNumber: number;
    name: string;
    abbreviatedName: string;
    returnLastWeekPercent: number | null;
    returnLastMonthPercent: number | null;
    returnLast3MonthsPercent: number | null;
    returnLastYearPercent: number | null;
};

export type DashboardFundCategoryApiModel = {
    title: string;
    /**
     * Unique identifier of report category
     */
    identifier: number;
    funds: Array<DashboardFundApiModel>;
};

export type DashboardItemApiModel = {
    identifier: number;
    order: number;
    report: DashboardItemReportApiModel;
    selectedFilters: {
    [key: string]: unknown;
} | null;
};

export type DashboardItemPreviewApiModel = {
    identifier: number;
    order: number;
    reportPreview: DashboardReportPreviewApiModel;
};

export type DashboardItemReportApiModel = {
    /**
     * Unique identifier of report
     */
    identifier: number;
    title: string;
    category: FinancialReportCategoryApiModel;
    reportCalculation: FinancialReportCalculationApiModel | null;
};

export type DashboardListItemApiModel = {
    identifier: number;
    name: string;
};

export type DashboardReportPreviewApiModel = {
    identifier: number;
    title: string;
    image: string;
};

export type DeleteDashboardItemFromDashboardBody = {
    dashboardItemId: number;
};

export type FinancialReportCalculationApiModel = {
    calculation: Report2CalculationResult | Report6CalculationResult | Report13Dot1CalculationResult | Report13Dot2CalculationResult | Report13Dot3CalculationResult | Report15CalculationResult;
    filters: Array<FinancialReportFilterApiModel>;
};

export type FinancialReportCategoryApiModel = {
    title: string;
    /**
     * Unique identifier of report category
     */
    identifier: number;
};

export type FinancialReportDetailsApiModel = {
    /**
     * Unique identifier of report
     */
    identifier: number;
    title: string;
    category: FinancialReportCategoryApiModel;
    image: string;
    summary: string;
    markdownDescription: string | null;
    video: VideoApiModel | null;
    userFavorite?: boolean;
    isNew?: boolean;
    relatedReports: Array<FinancialReportListItemApiModel>;
    reportCalculation: FinancialReportCalculationApiModel | null;
};

export type FinancialReportFilterApiModel = {
    parentTitle: string | null;
    title: string;
    searchable: boolean;
    options: Array<FinancialReportFilterOptionDto>;
    selectedOption: FinancialReportFilterOptionDto;
    optionType: string;
};

export type FinancialReportFilterOptionDto = {
    identifier: string;
    title: string;
};

export type FinancialReportListItemApiModel = {
    /**
     * Unique identifier of report
     */
    identifier: number;
    title: string;
    category: FinancialReportCategoryApiModel;
    image: string;
    summary: string;
    hasVideo?: boolean;
    userFavorite?: boolean;
    isNew?: boolean;
};

export type ForgotPasswordResetByOtpBody = {
    otp: string;
    newPassword: string;
    userId: number;
};

export type FundListItemApiModel = {
    identifier: number;
    registrationNumber: number;
    name: string;
    abbreviatedName: string;
    fundType: FundTypeApiModel;
    logoMedium: string | null;
    logoThumbnail: string | null;
    website: string;
    statuteUrl: string;
    prospectusUrl: string;
    isEtf: boolean;
    isCharity: boolean;
    manager: string;
    custodian: string;
    auditor: string;
    liquidityGuarantor: string;
    /**
     * Gregorian date of fund initiation in YYYY-mm-dd format
     */
    initiationDate: string;
    /**
     * Jalali date of fund initiation in YYYY-mm-dd format
     */
    initiationJdate: string;
    issueNavRials: number;
    redeemNavRials: number;
    statisticalNavRials: number;
    assetUnderManagementRials: number;
    numberOfUnits: number;
    returnLastWeekPercent: number | null;
    returnLastMonthPercent: number | null;
    returnLast3MonthsPercent: number | null;
    returnLastYearPercent: number | null;
    returnLastWeekVsTedpixPercent: number | null;
    returnLastMonthVsTedpixPercent: number | null;
    returnLast3MonthsVsTedpixPercent: number | null;
    returnLastYearVsTedpixPercent: number | null;
    assetAllocationBondPercent: number;
    assetAllocationBankDepositPercent: number;
    assetAllocationCommodityDepositCertificatePercent: number;
    assetAllocationCashPercent: number;
    assetAllocationStocksIncludingTop5Percent: number;
    assetAllocationFundUnitsPercent: number;
    assetAllocationOtherPercent: number;
    assetAllocationTop5StocksPercent: number;
    averageLeverageLastWeek: number | null;
    averageLeverageLastMonth: number | null;
    averageLeverageLast3Months: number | null;
    averageLeverageLastYear: number | null;
    standardDeviationLastWeek: number | null;
    standardDeviationLastMonth: number | null;
    standardDeviationLast3Month: number | null;
    standardDeviationLastYear: number | null;
    sharpeRatioLastWeek: number | null;
    sharpeRatioLastMonth: number | null;
    sharpeRatioLast3Months: number | null;
    sharpeRatioLastYear: number | null;
    informationRatioLastWeek: number | null;
    informationRatioLastMonth: number | null;
    informationRatioLast3Months: number | null;
    informationRatioLastYear: number | null;
    alphaLastDay: number | null;
    alphaLastWeek: number | null;
    alphaLastMonth: number | null;
    alphaLast3Months: number | null;
    alphaLastYear: number | null;
    betaLastDay: number | null;
    betaLastWeek: number | null;
    betaLastMonth: number | null;
    betaLast3Months: number | null;
    betaLastYear: number | null;
    maxDrawDawnWeek: number | null;
    maxDrawDawnMonth: number | null;
    maxDrawDawn3Month: number | null;
    maxDrawDawnYear: number | null;
};

export type FundTableResponseApiModel = {
    tabs: Array<FundTableTabApiModel>;
    selectedTabIdentifier: number;
    selectedTabFunds: Array<FundsTableItemApiModel>;
};

export type FundTableTabApiModel = {
    identifier: number;
    title: string;
    colorHexRgb: string | null;
};

export type FundTypeApiModel = {
    identifier: number;
    title: string;
};

export type FundsTableItemApiModel = {
    fund: FundListItemApiModel;
    pinned: boolean;
};

export type GetDashboardItemCalculationsBody = {
    dashboardItemId: number;
    selectedFilters?: {
    [key: string]: unknown;
} | null;
};

export type GetForgotPasswordOtpBody = {
    nationalCode: string;
    phoneNumber: string;
    captchaUid: number;
    captchaValue: string;
};

export type GetOtpForChangePasswordResponseApiModel = {
    retrySeconds: number;
    phoneNumber: string;
    userId: number;
};

export type GetOtpForForgotPasswordResponseApiModel = {
    retrySeconds: number;
    phoneNumber: string;
    userId: number;
};

export type GetReportCalculationsBody = {
    selectedFilters: {
    [key: string]: unknown;
} | null;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthApiModel = {
    status: string;
};

export type PinFundInTableTabBody = {
    tab: number;
    fund: number;
};

export type PinFundInTableTabResponseApiModel = {
    success: boolean;
};

export type RenameDashboardForUserBody = {
    name: string;
};

export type Report13Dot1CalculationResult = {
    lastDay: Report13Dot1CalculationResultColumn;
    lastDayNormalized: Report13Dot1CalculationResultColumnNormalized;
    maxValue: Report13Dot1CalculationResultColumn;
    minValue: Report13Dot1CalculationResultColumn;
    averageValue: Report13Dot1CalculationResultColumn;
};

export type Report13Dot1CalculationResultColumn = {
    totalTrades: number;
    totalBuyIndividual: number;
    totalBuyCorporate: number;
    totalSellIndividual: number;
    totalSellCorporate: number;
};

export type Report13Dot1CalculationResultColumnNormalized = {
    totalTradesNormalized: number;
    totalBuyIndividualNormalized: number;
    totalBuyCorporateNormalized: number;
    totalSellIndividualNormalized: number;
    totalSellCorporateNormalized: number;
};

export type Report13Dot2CalculationResult = {
    data: Report13Dot2CalculationResultItem;
};

export type Report13Dot2CalculationResultItem = {
    mean: number;
    median: number;
    lastTrade: number;
    kdePoints: Array<Report13Dot2GraphKdeResultItem>;
    histPoints: Array<Report13Dot2GraphHistResultItem>;
};

export type Report13Dot2GraphHistResultItem = {
    xMin: number;
    xMax: number;
    y: number;
};

export type Report13Dot2GraphKdeResultItem = {
    x: number;
    y: number;
};

export type Report13Dot3CalculationResult = {
    data: Array<Report13Dot3CalculationResultItem>;
};

export type Report13Dot3CalculationResultItem = {
    points: Array<Report13Dot3CalculationResultPoints>;
    mean: number;
};

export type Report13Dot3CalculationResultPoints = {
    date: string;
    value: number;
};

export type Report15CalculationResult = {
    beta: number;
    betaAdjusted: number;
    yIntersect: number;
    rSquared: number;
    pValue: number;
    graphData: Array<Report15CalculationResultGraphPoint>;
};

export type Report15CalculationResultGraphPoint = {
    x: number;
    y: number;
};

export type Report2CalculationResult = {
    data: Array<Report2CalculationResultItem>;
};

export type Report2CalculationResultItem = {
    sectorTitle: string;
    netFlow: number;
};

export type Report6CalculationResult = {
    data: Array<Report6CalculationResultTimeSeriesItem>;
};

export type Report6CalculationResultTimeSeriesItem = {
    dt: string;
    indexValue: number;
    netFlow: number;
};

export type ResetForgotPasswordByOtpResponseApiModel = {
    success: boolean;
};

export type TokenApiModel = {
    access_token: string;
    token_type: string;
};

export type UnpinFundInTableTabBody = {
    tab: number;
    fund: number;
};

export type UnpinFundInTableTabResponseApiModel = {
    success: boolean;
};

export type UserReportFavoriteStatus = {
    userId: number;
    reportId: number;
    isFavorite: boolean;
};

export type ValidatePasswordForUserBody = {
    password: string;
};

export type ValidatePasswordForUserResponseApiModel = {
    passwordVerificationToken: string;
    success: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VideoApiModel = {
    /**
     * Unique identifier of video
     */
    identifier: number;
    /**
     * Title of video
     */
    title: string;
    /**
     * Description of video
     */
    description: string | null;
    /**
     * Url of mp4 video file in 1080p
     */
    mp4Video1080P: string | null;
    /**
     * Size of 1080p mp4 video file in bytes
     */
    mp4Video1080PSizeBytes: number | null;
    /**
     * Url of mp4 video file in 720p
     */
    mp4Video720P: string | null;
    /**
     * Size of 720p mp4 video file in bytes
     */
    mp4Video720PSizeBytes: number | null;
    /**
     * Url of mp4 video file in 480p
     */
    mp4Video480P: string | null;
    /**
     * Size of 480p mp4 video file in bytes
     */
    mp4Video480PSizeBytes: number | null;
    /**
     * Url of mp4 video file in 360p
     */
    mp4Video360P: string | null;
    /**
     * Size of 360p mp4 video file in bytes
     */
    mp4Video360PSizeBytes: number | null;
    /**
     * Url of mp4 video file in 240p
     */
    mp4Video240P: string;
    /**
     * Size of 240p mp4 video file in bytes
     */
    mp4Video240PSizeBytes: number;
    /**
     * Duration of video in seconds
     */
    durationInSeconds: number;
    /**
     * Poster (placeholder) image of video
     */
    poster: string;
    /**
     * Thumbnail of video
     */
    thumbnailImages: Array<VideoThumbnailApiModel>;
};

export type VideoThumbnailApiModel = {
    /**
     * From which second we should use this video thumbnail
     */
    startTimeSeconds: number;
    /**
     * After start time, until how many seconds use this video thumbnail
     */
    durationSeconds: number;
    /**
     * Thumbnail file
     */
    image: string;
    /**
     * Interval in seconds between images
     */
    intervalSeconds: number;
    /**
     * Width of each thumbnail in pixes
     */
    widthPixels: number;
    /**
     * Height of each thumbnail in pixes
     */
    heightPixels: number;
    /**
     * Number of thumbnails per line
     */
    columns: number;
};

export type GetHealthResponse = HealthApiModel;

export type GetUsersLoginCaptchaData = {
    captchaHeight?: number;
    captchaType?: CaptchaType;
    captchaWidth?: number;
};

export type GetUsersLoginCaptchaResponse = CaptchaApiModel;

export type PostUsersLoginData = {
    captcha: string | null;
    captchaUid: number | null;
    formData: Body_login_for_access_token_users_login_post;
};

export type PostUsersLoginResponse = TokenApiModel;

export type PostUsersTokenData = {
    formData: Body_test_user_access_token_users_token_post;
};

export type PostUsersTokenResponse = TokenApiModel;

export type GetUsersMeResponse = AressApiUser | AnonymousApiUser;

export type PostUsersPasswordForgotCaptchaData = {
    captchaHeight?: number;
    captchaType?: CaptchaType;
    captchaWidth?: number;
};

export type PostUsersPasswordForgotCaptchaResponse = CaptchaApiModel;

export type PostUsersPasswordForgotOtpData = {
    requestBody: GetForgotPasswordOtpBody;
};

export type PostUsersPasswordForgotOtpResponse = GetOtpForForgotPasswordResponseApiModel;

export type PostUsersPasswordForgotResetData = {
    requestBody: ForgotPasswordResetByOtpBody;
};

export type PostUsersPasswordForgotResetResponse = ResetForgotPasswordByOtpResponseApiModel;

export type GetUsersProfilePasswordChangeOtpResponse = GetOtpForChangePasswordResponseApiModel;

export type PostUsersProfilePasswordChangeData = {
    requestBody: ChangePasswordByOtpBody;
};

export type PostUsersProfilePasswordChangeResponse = ChangePasswordByOtpApiModel;

export type PostUsersProfilePasswordValidateData = {
    requestBody: ValidatePasswordForUserBody;
};

export type PostUsersProfilePasswordValidateResponse = ValidatePasswordForUserResponseApiModel;

export type PostUsersProfilePhoneChangeOtpData = {
    requestBody: ChangePhoneGetOtpBody;
};

export type PostUsersProfilePhoneChangeOtpResponse = ChangePhoneGetOtpResponseApiModel;

export type PostUsersProfilePhoneChangeData = {
    requestBody: ChangePhoneByOtpBody;
};

export type PostUsersProfilePhoneChangeResponse = ChangePhoneByOtpResponseApiModel;

export type PostUsersProfileUsernameChangeData = {
    requestBody: ChangeUsernameBody;
};

export type PostUsersProfileUsernameChangeResponse = ChangeUsernameResponseApiModel;

export type PostUsersProfilePictureChangeData = {
    formData: Body_change_profile_picture_users_profile_picture_change_post;
};

export type PostUsersProfilePictureChangeResponse = ChangeProfilePictureResponseApiModel;

export type GetReportsData = {
    onlyFavorite?: boolean | null;
    onlyHavingVideo?: boolean | null;
    onlyNew?: boolean | null;
};

export type GetReportsResponse = Array<FinancialReportListItemApiModel>;

export type GetReportsByReportIdData = {
    reportId: number;
};

export type GetReportsByReportIdResponse = FinancialReportDetailsApiModel;

export type PostReportsByReportIdData = {
    reportId: number;
    requestBody: GetReportCalculationsBody;
};

export type PostReportsByReportIdResponse = FinancialReportCalculationApiModel;

export type GetReportsCategoriesResponse = Array<FinancialReportCategoryApiModel>;

export type PostReportsByReportIdFavoriteData = {
    reportId: number;
};

export type PostReportsByReportIdFavoriteResponse = UserReportFavoriteStatus;

export type DeleteReportsByReportIdFavoriteData = {
    reportId: number;
};

export type DeleteReportsByReportIdFavoriteResponse = UserReportFavoriteStatus;

export type GetDashboardsResponse = Array<DashboardListItemApiModel>;

export type PutDashboardsData = {
    requestBody: CreateDashboardForUserBody;
};

export type PutDashboardsResponse = DashboardListItemApiModel;

export type PostDashboardsByDashboardIdData = {
    dashboardId: number;
    requestBody: RenameDashboardForUserBody;
};

export type PostDashboardsByDashboardIdResponse = DashboardListItemApiModel;

export type DeleteDashboardsByDashboardIdData = {
    dashboardId: number;
};

export type DeleteDashboardsByDashboardIdResponse = unknown;

export type GetDashboardsByDashboardIdData = {
    dashboardId: number;
};

export type GetDashboardsByDashboardIdResponse = DashboardDetailsApiModel;

export type GetDashboardsByDashboardIdItemsPreviewData = {
    dashboardId: number;
};

export type GetDashboardsByDashboardIdItemsPreviewResponse = Array<DashboardItemPreviewApiModel>;

export type PutDashboardsByDashboardIdItemsData = {
    dashboardId: number;
    requestBody: AddReportToDashboardForUserBody;
};

export type PutDashboardsByDashboardIdItemsResponse = DashboardItemApiModel;

export type DeleteDashboardsByDashboardIdItemsData = {
    dashboardId: number;
    requestBody: DeleteDashboardItemFromDashboardBody;
};

export type DeleteDashboardsByDashboardIdItemsResponse = unknown;

export type PostDashboardsByDashboardIdItemsData = {
    dashboardId: number;
    requestBody: GetDashboardItemCalculationsBody;
};

export type PostDashboardsByDashboardIdItemsResponse = DashboardItemApiModel;

export type PostDashboardsByDashboardIdItemsReorderData = {
    dashboardId: number;
    requestBody: ChangeDashboardReportItemSortOrderBody;
};

export type PostDashboardsByDashboardIdItemsReorderResponse = unknown;

export type GetFundsResponse = Array<FundListItemApiModel>;

export type GetFundsTypeByFundTypeData = {
    fundType: number;
};

export type GetFundsTypeByFundTypeResponse = Array<FundListItemApiModel>;

export type GetFundsTableData = {
    tab?: number;
};

export type GetFundsTableResponse = FundTableResponseApiModel;

export type PostFundsTablePinData = {
    requestBody: PinFundInTableTabBody;
};

export type PostFundsTablePinResponse = PinFundInTableTabResponseApiModel;

export type PostFundsTableUnpinData = {
    requestBody: UnpinFundInTableTabBody;
};

export type PostFundsTableUnpinResponse = UnpinFundInTableTabResponseApiModel;

export type $OpenApiTs = {
    '/health': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: HealthApiModel;
            };
        };
    };
    '/users/login/captcha': {
        get: {
            req: GetUsersLoginCaptchaData;
            res: {
                /**
                 * Successful Response
                 */
                200: CaptchaApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/login': {
        post: {
            req: PostUsersLoginData;
            res: {
                /**
                 * Successful Response
                 */
                200: TokenApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/token': {
        post: {
            req: PostUsersTokenData;
            res: {
                /**
                 * Successful Response
                 */
                200: TokenApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: AressApiUser | AnonymousApiUser;
            };
        };
    };
    '/users/password/forgot/captcha': {
        post: {
            req: PostUsersPasswordForgotCaptchaData;
            res: {
                /**
                 * Successful Response
                 */
                200: CaptchaApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/password/forgot/otp': {
        post: {
            req: PostUsersPasswordForgotOtpData;
            res: {
                /**
                 * Successful Response
                 */
                200: GetOtpForForgotPasswordResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/password/forgot/reset': {
        post: {
            req: PostUsersPasswordForgotResetData;
            res: {
                /**
                 * Successful Response
                 */
                200: ResetForgotPasswordByOtpResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/profile/password/change/otp': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: GetOtpForChangePasswordResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/profile/password/change': {
        post: {
            req: PostUsersProfilePasswordChangeData;
            res: {
                /**
                 * Successful Response
                 */
                200: ChangePasswordByOtpApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/profile/password/validate': {
        post: {
            req: PostUsersProfilePasswordValidateData;
            res: {
                /**
                 * Successful Response
                 */
                200: ValidatePasswordForUserResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/profile/phone/change/otp': {
        post: {
            req: PostUsersProfilePhoneChangeOtpData;
            res: {
                /**
                 * Successful Response
                 */
                200: ChangePhoneGetOtpResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/profile/phone/change': {
        post: {
            req: PostUsersProfilePhoneChangeData;
            res: {
                /**
                 * Successful Response
                 */
                200: ChangePhoneByOtpResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/profile/username/change': {
        post: {
            req: PostUsersProfileUsernameChangeData;
            res: {
                /**
                 * Successful Response
                 */
                200: ChangeUsernameResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/profile/picture/change': {
        post: {
            req: PostUsersProfilePictureChangeData;
            res: {
                /**
                 * Successful Response
                 */
                200: ChangeProfilePictureResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/reports': {
        get: {
            req: GetReportsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<FinancialReportListItemApiModel>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/reports/{report_id}': {
        get: {
            req: GetReportsByReportIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: FinancialReportDetailsApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PostReportsByReportIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: FinancialReportCalculationApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/reports/categories': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<FinancialReportCategoryApiModel>;
            };
        };
    };
    '/reports/{report_id}/favorite': {
        post: {
            req: PostReportsByReportIdFavoriteData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserReportFavoriteStatus;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteReportsByReportIdFavoriteData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserReportFavoriteStatus;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/dashboards': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<DashboardListItemApiModel>;
            };
        };
        put: {
            req: PutDashboardsData;
            res: {
                /**
                 * Successful Response
                 */
                200: DashboardListItemApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/dashboards/{dashboard_id}': {
        post: {
            req: PostDashboardsByDashboardIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: DashboardListItemApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteDashboardsByDashboardIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        get: {
            req: GetDashboardsByDashboardIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: DashboardDetailsApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/dashboards/{dashboard_id}/items/preview': {
        get: {
            req: GetDashboardsByDashboardIdItemsPreviewData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<DashboardItemPreviewApiModel>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/dashboards/{dashboard_id}/items': {
        put: {
            req: PutDashboardsByDashboardIdItemsData;
            res: {
                /**
                 * Successful Response
                 */
                200: DashboardItemApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteDashboardsByDashboardIdItemsData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PostDashboardsByDashboardIdItemsData;
            res: {
                /**
                 * Successful Response
                 */
                200: DashboardItemApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/dashboards/{dashboard_id}/items/reorder': {
        post: {
            req: PostDashboardsByDashboardIdItemsReorderData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/funds': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<FundListItemApiModel>;
            };
        };
    };
    '/funds/type/{fund_type}': {
        get: {
            req: GetFundsTypeByFundTypeData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<FundListItemApiModel>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/funds/table': {
        get: {
            req: GetFundsTableData;
            res: {
                /**
                 * Successful Response
                 */
                200: FundTableResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/funds/table/pin': {
        post: {
            req: PostFundsTablePinData;
            res: {
                /**
                 * Successful Response
                 */
                200: PinFundInTableTabResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/funds/table/unpin': {
        post: {
            req: PostFundsTableUnpinData;
            res: {
                /**
                 * Successful Response
                 */
                200: UnpinFundInTableTabResponseApiModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};