// This file is auto-generated by @hey-api/openapi-ts

export type AddReportToDashboardForUserBody = {
  reportIdentifier: string;
  order: number;
  selectedFilters?: {
    [key: string]: unknown;
  } | null;
};

export type AnonymousApiUser = {
  [key: string]: unknown;
};

export type AressApiUser = {
  /**
   * Unique identifier of user
   */
  identifier: number;
  /**
   * Username for the user
   */
  username: string;
  /**
   * Email for the user.
   */
  email: string;
  /**
   * Phone number of the user.
   */
  phoneNumber: string | null;
  /**
   * National code of the user.
   */
  nationalCode: string | null;
  /**
   * Whether this user is active or not, is always "true" for logged in user.
   */
  active: boolean;
  /**
   * First name of user.
   */
  firstName: string | null;
  /**
   * Last name the user.
   */
  lastName: string | null;
  /**
   * Profile picture url of the user.
   */
  profilePicture: string | null;
};

export type Body_change_profile_picture_users_profile_picture_change_post = {
  file: Blob | File;
};

export type Body_login_for_access_token_users_login_post = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type Body_request_new_report_reports_request_post = {
  file: (Blob | File) | null;
  request_form: RequestReportForm;
};

export type Body_save_dashboard_item_screenshot_dashboards__dashboard_id__items__dashboard_item_id__screenshot_post =
  {
    file: Blob | File;
    selected_filters: string | null;
  };

export type Body_save_screenshot_reports__report_id__screenshot_post = {
  selected_filters: string | null;
  file: Blob | File;
};

export type Body_test_user_access_token_users_token_post = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type CaptchaApiModel = {
  value: string | null;
  uid: number | null;
  required: boolean;
};

export type CaptchaType = 'image' | 'audio';

export type ChangeDashboardReportItemSortOrderBody = {
  order: number;
};

export type ChangeEmailByOtpBody = {
  otp: string;
};

export type ChangeEmailByOtpResponseApiModel = {
  success: boolean;
};

export type ChangeEmailGetOtpBody = {
  newEmail: string;
  passwordVerificationToken: string;
};

export type ChangeEmailGetOtpResponseApiModel = {
  retrySeconds: number;
  email: string;
};

export type ChangePasswordByOtpApiModel = {
  success: boolean;
};

export type ChangePasswordByOtpBody = {
  otp: string;
  newPassword: string;
};

export type ChangePhoneByOtpBody = {
  otp: string;
};

export type ChangePhoneByOtpResponseApiModel = {
  success: boolean;
};

export type ChangePhoneGetOtpBody = {
  newPhoneNumber: string;
  passwordVerificationToken: string;
};

export type ChangePhoneGetOtpResponseApiModel = {
  retrySeconds: number;
  phoneNumber: string;
};

export type ChangeProfilePictureResponseApiModel = {
  success: boolean;
};

export type ChangeUsernameBody = {
  newUsername: string;
  passwordVerificationToken: string;
};

export type ChangeUsernameResponseApiModel = {
  success: boolean;
};

export type CreateDashboardForUserBody = {
  name: string;
};

export type CreateDashboardResponseApiModel = {
  createdDashboardId: number;
  dashboards: Array<DashboardListItemApiModel>;
};

export type DashboardDetailsApiModel = {
  identifier: number;
  name: string;
  items: Array<DashboardItemApiModel>;
  fundsByCategory: Array<DashboardFundCategoryApiModel>;
};

export type DashboardFundApiModel = {
  identifier: number;
  registrationNumber: number;
  name: string;
  abbreviatedName: string;
  returnLastWeekPercent: number | null;
  returnLastMonthPercent: number | null;
  returnLast3MonthsPercent: number | null;
  returnLastYearPercent: number | null;
  dailyRedeemNavMonth: Array<number> | null;
};

export type DashboardFundCategoryApiModel = {
  title: string;
  /**
   * Unique identifier of report category
   */
  identifier: number;
  funds: Array<DashboardFundApiModel>;
};

export type DashboardItemApiModel = {
  identifier: number;
  order: number;
  report: DashboardItemReportApiModel;
  selectedFilters: {
    [key: string]: unknown;
  } | null;
};

export type DashboardItemPreviewApiModel = {
  identifier: number;
  order: number;
  reportPreview: DashboardReportPreviewApiModel;
};

export type DashboardItemReportApiModel = {
  /**
   * Unique identifier of report
   */
  identifier: number;
  title: string;
  category: FinancialReportCategoryApiModel;
  reportCalculation: FinancialReportCalculationApiModel | null;
};

export type DashboardItemScreenshotResponseApiModel = {
  queryId: string;
  screenshotUrl: string;
};

export type DashboardListItemApiModel = {
  identifier: number;
  name: string;
};

export type DashboardReportPreviewApiModel = {
  identifier: number;
  title: string;
  image: string;
};

export type DeleteDashboardItemResponseApiModel = {
  [key: string]: unknown;
};

export type DuplicateDashboardForUserBody = {
  name: string;
};

export type FinancialReportCalculationApiModel = {
  calculation:
    | Report2CalculationResult
    | Report6CalculationResult
    | Report13Dot1CalculationResult
    | Report13Dot2CalculationResult
    | Report13Dot3CalculationResult
    | Report15CalculationResult
    | Report36CalculationResult
    | Report39CalculationResult;
  filters: Array<FinancialReportFilterApiModel>;
};

export type FinancialReportCategoryApiModel = {
  title: string;
  /**
   * Unique identifier of report category
   */
  identifier: number;
};

export type FinancialReportDetailsApiModel = {
  /**
   * Unique identifier of report
   */
  identifier: string;
  title: string;
  category: FinancialReportCategoryApiModel;
  image: string | null;
  summary: string;
  markdownDescription: string | null;
  video: VideoApiModel | null;
  userFavorite?: boolean;
  isNew?: boolean;
  relatedReports: Array<FinancialReportListItemApiModel>;
  reportCalculation: FinancialReportCalculationApiModel | null;
  screenshotUrl: string | null;
};

export type FinancialReportFilterApiModel = {
  parentTitle: string | null;
  title: string;
  searchable: boolean;
  options: Array<FinancialReportFilterOptionDto>;
  selectedOption: FinancialReportFilterOptionDto;
  optionType: string;
};

export type FinancialReportFilterOptionDto = {
  identifier: string;
  title: string;
};

export type FinancialReportListItemApiModel = {
  /**
   * Unique identifier of report
   */
  identifier: string;
  title: string;
  category: FinancialReportCategoryApiModel;
  image: string | null;
  summary: string;
  hasVideo?: boolean;
  userFavorite?: boolean;
  isNew?: boolean;
};

export type ForgotPasswordResetByOtpBody = {
  otp: string;
  newPassword: string;
  userId: number;
};

export type FundListItemApiModel = {
  /**
   * شناسه صندوق
   */
  identifier: number;
  /**
   * شماره ثبت نزد سازمان بورس
   */
  registrationNumber: number;
  /**
   * نام کامل صندوق
   */
  name: string;
  /**
   * نام صندوق
   */
  abbreviatedName: string;
  /**
   * نوع صندوق
   */
  fundType: FundTypeApiModel;
  /**
   * آدرس لوگوی صندوق - سایز متوسط
   */
  logoMedium: string | null;
  /**
   * آدرس لوگوی صندوق - سایز کوچک
   */
  logoThumbnail: string | null;
  /**
   * وبسایت صندوق
   */
  website: string | null;
  /**
   * اساسنامه صندوق
   */
  statuteUrl: string;
  /**
   * امیدنامه صندوق
   */
  prospectusUrl: string;
  /**
   * آیا صندوق etf است
   */
  isEtf: boolean;
  /**
   * آیا صندوق نیکوکاری است
   */
  isCharity: boolean;
  /**
   * دارای ویدیو بررسی
   */
  hasVideo: boolean;
  /**
   * مدیر صنودق
   */
  manager: string;
  /**
   * متولی صندوق
   */
  custodian: string;
  /**
   * حسابرس صندوق
   */
  auditor: string;
  /**
   * ضامن نقد شوندگی صندوق
   */
  liquidityGuarantor: string;
  /**
   * بازارگردان
   */
  marketMaker: string;
  /**
   * تاریخ آغاز فعالیت میلادی
   */
  initiationDate: string;
  /**
   * تاریخ آغاز فعالیت
   */
  initiationJdate: string;
  /**
   * قیمت صدور
   */
  issueNavRials: number;
  /**
   * قیمت ابطال
   */
  redeemNavRials: number;
  /**
   * قیمت آماری
   */
  statisticalNavRials: number;
  /**
   * دارایی تحت مدیریت
   */
  assetUnderManagementRials: number;
  /**
   * تعداد واحد
   */
  numberOfUnits: number;
  /**
   * بازدهی هفته اخیر
   */
  returnLastWeekPercent: number | null;
  /**
   * بازدهی ماه اخیر
   */
  returnLastMonthPercent: number | null;
  /**
   * بازدهی سه ماه اخیر
   */
  returnLast3MonthsPercent: number | null;
  /**
   * بازدهی سال اخیر
   */
  returnLastYearPercent: number | null;
  /**
   * بازدهی هفته اخیر به شاخص
   */
  returnLastWeekVsTedpixPercent: number | null;
  /**
   * بازدهی ماه اخیر به شاخص
   */
  returnLastMonthVsTedpixPercent: number | null;
  /**
   * بازدهی سه ماه اخیر به شاخص
   */
  returnLast3MonthsVsTedpixPercent: number | null;
  /**
   * بازدهی سال اخیر به شاخص
   */
  returnLastYearVsTedpixPercent: number | null;
  /**
   * سهم اوراق از پورتفوی
   */
  assetAllocationBondPercent: number;
  /**
   * سهم سپرده بانکی از پورتفوی
   */
  assetAllocationBankDepositPercent: number;
  /**
   * سهم گواهی سپرده کالایی از پورتفوی
   */
  assetAllocationCommodityDepositCertificatePercent: number;
  /**
   * سهم وجه نقد از پورتفوی
   */
  assetAllocationCashPercent: number;
  /**
   * سهم سهام از پورتفوی
   */
  assetAllocationStocksIncludingTop5Percent: number;
  /**
   * سهم واحد صندوق‌ها از پورتفوی
   */
  assetAllocationFundUnitsPercent: number;
  /**
   * سهم سایر از پورتفوی
   */
  assetAllocationOtherPercent: number;
  /**
   * سهم پنج سهم برتر از پورتفوی
   */
  assetAllocationTop5StocksPercent: number;
  /**
   * میانگین اهرم هفته اخیر
   */
  averageLeverageLastWeek: number | null;
  /**
   * میانگین اهرم ماه اخیر
   */
  averageLeverageLastMonth: number | null;
  /**
   * میانگین اهرم سه ماه اخیر
   */
  averageLeverageLast3Months: number | null;
  /**
   * میانگین اهرم سال اخیر
   */
  averageLeverageLastYear: number | null;
  /**
   * انحراف از میانگین هفته اخیر
   */
  standardDeviationLastWeek: number | null;
  /**
   * انحراف از میانگین ماه اخیر
   */
  standardDeviationLastMonth: number | null;
  /**
   * انحراف از میانگین سه ماه اخیر
   */
  standardDeviationLast3Month: number | null;
  /**
   * انحراف از میانگین سال اخیر
   */
  standardDeviationLastYear: number | null;
  /**
   * نسبت شارپی هفته اخیر
   */
  sharpeRatioLastWeek: number | null;
  /**
   * نسبت شارپی ماه اخیر
   */
  sharpeRatioLastMonth: number | null;
  /**
   * نسبت شارپی سه ماه اخیر
   */
  sharpeRatioLast3Months: number | null;
  /**
   * نسبت شارپی سال اخیر
   */
  sharpeRatioLastYear: number | null;
  /**
   * نسبت اصلاعاتی هفته اخیر
   */
  informationRatioLastWeek: number | null;
  /**
   * نسبت اصلاعاتی ماه اخیر
   */
  informationRatioLastMonth: number | null;
  /**
   * نسبت اصلاعاتی سه ماه اخیر
   */
  informationRatioLast3Months: number | null;
  /**
   * نسبت اصلاعاتی سال اخیر
   */
  informationRatioLastYear: number | null;
  /**
   * آلفا روز اخیر
   */
  alphaLastDay: number | null;
  /**
   * آلفا هفته اخیر
   */
  alphaLastWeek: number | null;
  /**
   * آلفا ماه اخیر
   */
  alphaLastMonth: number | null;
  /**
   * آلفا سه ماه اخیر
   */
  alphaLast3Months: number | null;
  /**
   * آلفا سال اخیر
   */
  alphaLastYear: number | null;
  /**
   * بتا روز اخیر
   */
  betaLastDay: number | null;
  /**
   * بتا هفته اخیر
   */
  betaLastWeek: number | null;
  /**
   * بتا ماه اخیر
   */
  betaLastMonth: number | null;
  /**
   * بتا سه ماه اخیر
   */
  betaLast3Months: number | null;
  /**
   * بتا سال اخیر
   */
  betaLastYear: number | null;
  /**
   * ماکزیمم افت هفته اخیر
   */
  maxDrawdownWeek: number | null;
  /**
   * ماکزیمم افت ماه اخیر
   */
  maxDrawdownMonth: number | null;
  /**
   * ماکزیمم افت سه ماه اخیر
   */
  maxDrawdown3Month: number | null;
  /**
   * ماکزیمم افت سال اخیر
   */
  maxDrawdownYear: number | null;
  /**
   * قیمت ابطال روزانه ماه اخیر
   */
  dailyRedeemNavMonth: Array<number> | null;
};

export type FundTableResponseApiModel = {
  tabs: Array<FundTableTabApiModel>;
  selectedTabIdentifier: number;
  selectedTabFunds: Array<FundsTableItemApiModel>;
};

export type FundTableTabApiModel = {
  identifier: number;
  title: string;
  color: string | null;
};

export type FundTypeApiModel = {
  identifier: number;
  title: string;
};

export type FundsTableItemApiModel = {
  fund: FundListItemApiModel;
  pinned: boolean;
};

export type GetDashboardItemCalculationsBody = {
  selectedFilters?: {
    [key: string]: unknown;
  } | null;
};

export type GetForgotPasswordOtpBody = {
  nationalCode: string;
  phoneNumber: string;
  captchaUid: number;
  captchaValue: string;
};

export type GetOtpForChangePasswordResponseApiModel = {
  retrySeconds: number;
  phoneNumber: string;
  userId: number;
};

export type GetOtpForForgotPasswordResponseApiModel = {
  retrySeconds: number;
  phoneNumber: string;
  userId: number;
};

export type GetReportCalculationsBody = {
  selectedFilters: {
    [key: string]: unknown;
  } | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type HealthApiModel = {
  status: string;
};

export type LogoutResponseApiModel = {
  success: boolean;
};

export type PinFundInTableTabBody = {
  tab: number;
  fund: number;
};

export type PinFundInTableTabResponseApiModel = {
  success: boolean;
};

export type RenameDashboardForUserBody = {
  name: string;
};

export type ReplaceDashboardItemCalculationsBody = {
  newReportIdentifier: string;
};

export type Report13Dot1CalculationResult = {
  lastDay: Report13Dot1CalculationResultColumn;
  lastDayNormalized: Report13Dot1CalculationResultColumnNormalized;
  maxValue: Report13Dot1CalculationResultColumn;
  minValue: Report13Dot1CalculationResultColumn;
  averageValue: Report13Dot1CalculationResultColumn;
};

export type Report13Dot1CalculationResultColumn = {
  totalTrades: number;
  totalBuyIndividual: number;
  totalBuyCorporate: number;
  totalSellIndividual: number;
  totalSellCorporate: number;
};

export type Report13Dot1CalculationResultColumnNormalized = {
  totalTradesNormalized: number;
  totalBuyIndividualNormalized: number;
  totalBuyCorporateNormalized: number;
  totalSellIndividualNormalized: number;
  totalSellCorporateNormalized: number;
};

export type Report13Dot2CalculationResult = {
  data: Report13Dot2CalculationResultItem;
};

export type Report13Dot2CalculationResultItem = {
  mean: number;
  median: number;
  lastTrade: number;
  kdePoints: Array<Report13Dot2GraphKdeResultItem>;
  histPoints: Array<Report13Dot2GraphHistResultItem>;
};

export type Report13Dot2GraphHistResultItem = {
  xMin: number;
  xMax: number;
  y: number;
};

export type Report13Dot2GraphKdeResultItem = {
  x: number;
  y: number;
};

export type Report13Dot3CalculationResult = {
  data: Array<Report13Dot3CalculationResultItem>;
};

export type Report13Dot3CalculationResultItem = {
  points: Array<Report13Dot3CalculationResultPoints>;
  mean: number;
};

export type Report13Dot3CalculationResultPoints = {
  date: string;
  value: number;
};

export type Report15CalculationResult = {
  beta: number;
  betaAdjusted: number;
  yIntersect: number;
  rSquared: number;
  pValue: number;
  graphData: Array<Report15CalculationResultGraphPoint>;
};

export type Report15CalculationResultGraphPoint = {
  x: number;
  y: number;
  tradeDateShamsi: string;
};

export type Report2CalculationResult = {
  data: Array<Report2CalculationResultItem>;
  unit: string;
};

export type Report2CalculationResultItem = {
  sectorTitle: string;
  netFlow: number;
};

export type Report36CalculationResult = {
  buckets: Array<Report36CalculationResultBucket>;
  positiveInstruments: number;
  negativeInstruments: number;
  bucketRangeUnit: string;
  bucketCountUnit: string;
};

export type Report36CalculationResultBucket = {
  bucketMin: number | null;
  bucketMax: number | null;
  displayBucketAverage: number;
  bucketInstrumentsCount: number;
};

export type Report39CalculationResult = {
  data: Array<Report39CalculationResultItem>;
};

export type Report39CalculationResultItem = {
  values: Array<Report39InstrumentsResultItem>;
};

export type Report39InstrumentsResultItem = {
  instrument: string;
  netFlow: number;
  unit: string;
};

export type Report6CalculationResult = {
  data: Array<Report6CalculationResultTimeSeriesItem>;
};

export type Report6CalculationResultTimeSeriesItem = {
  dt: string;
  indexValue: number;
  netFlow: number;
};

export type ReportScreenshotResponseApiModel = {
  queryId: string;
  screenshotUrl: string;
};

export type RequestReportForm = {
  title: string;
  text: string;
  call: string;
};

export type RequestReportResponseApiModel = {
  requestFollowCode: number;
  success: boolean;
};

export type ResetForgotPasswordByOtpResponseApiModel = {
  success: boolean;
};

export type TokenApiModel = {
  access_token: string;
  token_type: string;
};

export type UnpinFundInTableTabBody = {
  tab: number;
  fund: number;
};

export type UnpinFundInTableTabResponseApiModel = {
  success: boolean;
};

export type UserReportFavoriteStatus = {
  userId: number;
  reportId: number;
  isFavorite: boolean;
};

export type ValidatePasswordForUserBody = {
  password: string;
};

export type ValidatePasswordForUserResponseApiModel = {
  passwordVerificationToken: string;
  success: boolean;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type VideoApiModel = {
  /**
   * Unique identifier of video
   */
  identifier: number;
  /**
   * Title of video
   */
  title: string;
  /**
   * Description of video
   */
  description: string | null;
  /**
   * Url of mp4 video file in 1080p
   */
  mp4Video1080P: string | null;
  /**
   * Size of 1080p mp4 video file in bytes
   */
  mp4Video1080PSizeBytes: number | null;
  /**
   * Url of mp4 video file in 720p
   */
  mp4Video720P: string | null;
  /**
   * Size of 720p mp4 video file in bytes
   */
  mp4Video720PSizeBytes: number | null;
  /**
   * Url of mp4 video file in 480p
   */
  mp4Video480P: string | null;
  /**
   * Size of 480p mp4 video file in bytes
   */
  mp4Video480PSizeBytes: number | null;
  /**
   * Url of mp4 video file in 360p
   */
  mp4Video360P: string | null;
  /**
   * Size of 360p mp4 video file in bytes
   */
  mp4Video360PSizeBytes: number | null;
  /**
   * Url of mp4 video file in 240p
   */
  mp4Video240P: string;
  /**
   * Size of 240p mp4 video file in bytes
   */
  mp4Video240PSizeBytes: number;
  /**
   * Duration of video in seconds
   */
  durationInSeconds: number;
  /**
   * Poster (placeholder) image of video
   */
  poster: string;
  /**
   * Thumbnail of video
   */
  thumbnailImages: Array<VideoThumbnailApiModel>;
};

export type VideoThumbnailApiModel = {
  /**
   * From which second we should use this video thumbnail
   */
  startTimeSeconds: number;
  /**
   * After start time, until how many seconds use this video thumbnail
   */
  durationSeconds: number;
  /**
   * Thumbnail file
   */
  image: string;
  /**
   * Interval in seconds between images
   */
  intervalSeconds: number;
  /**
   * Width of each thumbnail in pixes
   */
  widthPixels: number;
  /**
   * Height of each thumbnail in pixes
   */
  heightPixels: number;
  /**
   * Number of thumbnails per line
   */
  columns: number;
};

export type GetHealthResponse = HealthApiModel;

export type GetUsersLoginCaptchaData = {
  captchaHeight?: number;
  captchaType?: CaptchaType;
  captchaWidth?: number;
};

export type GetUsersLoginCaptchaResponse = CaptchaApiModel;

export type PostUsersLoginData = {
  captcha: string | null;
  captchaUid: number | null;
  formData: Body_login_for_access_token_users_login_post;
};

export type PostUsersLoginResponse = TokenApiModel;

export type PostUsersTokenData = {
  formData: Body_test_user_access_token_users_token_post;
};

export type PostUsersTokenResponse = TokenApiModel;

export type GetUsersMeResponse = AressApiUser | AnonymousApiUser;

export type GetUsersPasswordForgotCaptchaData = {
  captchaHeight?: number;
  captchaType?: CaptchaType;
  captchaWidth?: number;
};

export type GetUsersPasswordForgotCaptchaResponse = CaptchaApiModel;

export type PostUsersPasswordForgotOtpData = {
  requestBody: GetForgotPasswordOtpBody;
};

export type PostUsersPasswordForgotOtpResponse =
  GetOtpForForgotPasswordResponseApiModel;

export type PostUsersPasswordForgotResetData = {
  requestBody: ForgotPasswordResetByOtpBody;
};

export type PostUsersPasswordForgotResetResponse =
  ResetForgotPasswordByOtpResponseApiModel;

export type GetUsersProfilePasswordChangeOtpResponse =
  GetOtpForChangePasswordResponseApiModel;

export type PostUsersProfilePasswordChangeData = {
  requestBody: ChangePasswordByOtpBody;
};

export type PostUsersProfilePasswordChangeResponse =
  ChangePasswordByOtpApiModel;

export type PostUsersProfilePasswordValidateData = {
  requestBody: ValidatePasswordForUserBody;
};

export type PostUsersProfilePasswordValidateResponse =
  ValidatePasswordForUserResponseApiModel;

export type PostUsersProfilePhoneChangeOtpData = {
  requestBody: ChangePhoneGetOtpBody;
};

export type PostUsersProfilePhoneChangeOtpResponse =
  ChangePhoneGetOtpResponseApiModel;

export type PostUsersProfilePhoneChangeData = {
  requestBody: ChangePhoneByOtpBody;
};

export type PostUsersProfilePhoneChangeResponse =
  ChangePhoneByOtpResponseApiModel;

export type PostUsersProfileEmailChangeOtpData = {
  requestBody: ChangeEmailGetOtpBody;
};

export type PostUsersProfileEmailChangeOtpResponse =
  ChangeEmailGetOtpResponseApiModel;

export type PostUsersProfileEmailChangeData = {
  requestBody: ChangeEmailByOtpBody;
};

export type PostUsersProfileEmailChangeResponse =
  ChangeEmailByOtpResponseApiModel;

export type PostUsersProfileUsernameChangeData = {
  requestBody: ChangeUsernameBody;
};

export type PostUsersProfileUsernameChangeResponse =
  ChangeUsernameResponseApiModel;

export type PostUsersProfilePictureChangeData = {
  formData: Body_change_profile_picture_users_profile_picture_change_post;
};

export type PostUsersProfilePictureChangeResponse =
  ChangeProfilePictureResponseApiModel;

export type PostUsersLogoutResponse = LogoutResponseApiModel;

export type GetReportsData = {
  onlyFavorite?: boolean | null;
  onlyHavingVideo?: boolean | null;
  onlyNew?: boolean | null;
};

export type GetReportsResponse = Array<FinancialReportListItemApiModel>;

export type GetReportsCategoriesResponse =
  Array<FinancialReportCategoryApiModel>;

export type PostReportsRequestData = {
  formData: Body_request_new_report_reports_request_post;
};

export type PostReportsRequestResponse = RequestReportResponseApiModel;

export type GetReportsByReportIdData = {
  reportId: string;
  screenshotQueryId?: string | null;
};

export type GetReportsByReportIdResponse = FinancialReportDetailsApiModel;

export type PostReportsByReportIdData = {
  reportId: string;
  requestBody: GetReportCalculationsBody;
};

export type PostReportsByReportIdResponse = FinancialReportCalculationApiModel;

export type PostReportsByReportIdFavoriteData = {
  reportId: string;
};

export type PostReportsByReportIdFavoriteResponse = UserReportFavoriteStatus;

export type DeleteReportsByReportIdFavoriteData = {
  reportId: string;
};

export type DeleteReportsByReportIdFavoriteResponse = UserReportFavoriteStatus;

export type PostReportsByReportIdScreenshotData = {
  formData: Body_save_screenshot_reports__report_id__screenshot_post;
  reportId: string;
};

export type PostReportsByReportIdScreenshotResponse =
  ReportScreenshotResponseApiModel;

export type GetDashboardsResponse = Array<DashboardListItemApiModel>;

export type PutDashboardsData = {
  requestBody: CreateDashboardForUserBody;
};

export type PutDashboardsResponse = CreateDashboardResponseApiModel;

export type GetDashboardsByDashboardIdData = {
  dashboardId: number;
};

export type GetDashboardsByDashboardIdResponse = DashboardDetailsApiModel;

export type PostDashboardsByDashboardIdData = {
  dashboardId: number;
  requestBody: RenameDashboardForUserBody;
};

export type PostDashboardsByDashboardIdResponse = DashboardListItemApiModel;

export type DeleteDashboardsByDashboardIdData = {
  dashboardId: number;
};

export type DeleteDashboardsByDashboardIdResponse =
  Array<DashboardListItemApiModel>;

export type PutDashboardsByDashboardIdData = {
  dashboardId: number;
  requestBody: AddReportToDashboardForUserBody;
};

export type PutDashboardsByDashboardIdResponse = DashboardItemApiModel;

export type PostDashboardsByDashboardIdDuplicateData = {
  dashboardId: number;
  requestBody: DuplicateDashboardForUserBody;
};

export type PostDashboardsByDashboardIdDuplicateResponse =
  DashboardDetailsApiModel;

export type GetDashboardsByDashboardIdPreviewData = {
  dashboardId: number;
};

export type GetDashboardsByDashboardIdPreviewResponse =
  Array<DashboardItemPreviewApiModel>;

export type DeleteDashboardsByDashboardIdItemsByDashboardItemIdData = {
  dashboardId: number;
  dashboardItemId: number;
};

export type DeleteDashboardsByDashboardIdItemsByDashboardItemIdResponse =
  DeleteDashboardItemResponseApiModel;

export type PostDashboardsByDashboardIdItemsByDashboardItemIdReplaceData = {
  dashboardId: number;
  dashboardItemId: number;
  requestBody: ReplaceDashboardItemCalculationsBody;
};

export type PostDashboardsByDashboardIdItemsByDashboardItemIdReplaceResponse =
  DashboardItemApiModel;

export type PostDashboardsByDashboardIdItemsByDashboardItemIdScreenshotData = {
  dashboardId: number;
  dashboardItemId: number;
  formData: Body_save_dashboard_item_screenshot_dashboards__dashboard_id__items__dashboard_item_id__screenshot_post;
};

export type PostDashboardsByDashboardIdItemsByDashboardItemIdScreenshotResponse =
  DashboardItemScreenshotResponseApiModel;

export type PostDashboardsByDashboardIdItemsByDashboardItemIdCalculationsData =
  {
    dashboardId: number;
    dashboardItemId: number;
    requestBody: GetDashboardItemCalculationsBody;
  };

export type PostDashboardsByDashboardIdItemsByDashboardItemIdCalculationsResponse =
  DashboardItemApiModel;

export type PostDashboardsByDashboardIdItemsByDashboardItemIdReorderData = {
  dashboardId: number;
  dashboardItemId: number;
  requestBody: ChangeDashboardReportItemSortOrderBody;
};

export type PostDashboardsByDashboardIdItemsByDashboardItemIdReorderResponse =
  unknown;

export type GetFundsResponse = Array<FundListItemApiModel>;

export type GetFundsTypeByFundTypeData = {
  fundType: number;
};

export type GetFundsTypeByFundTypeResponse = Array<FundListItemApiModel>;

export type GetFundsTableData = {
  tab?: number;
};

export type GetFundsTableResponse = FundTableResponseApiModel;

export type PostFundsTablePinData = {
  requestBody: PinFundInTableTabBody;
};

export type PostFundsTablePinResponse = PinFundInTableTabResponseApiModel;

export type PostFundsTableUnpinData = {
  requestBody: UnpinFundInTableTabBody;
};

export type PostFundsTableUnpinResponse = UnpinFundInTableTabResponseApiModel;

export type $OpenApiTs = {
  '/health': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: HealthApiModel;
      };
    };
  };
  '/users/login/captcha': {
    get: {
      req: GetUsersLoginCaptchaData;
      res: {
        /**
         * Successful Response
         */
        200: CaptchaApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/login': {
    post: {
      req: PostUsersLoginData;
      res: {
        /**
         * Successful Response
         */
        200: TokenApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/token': {
    post: {
      req: PostUsersTokenData;
      res: {
        /**
         * Successful Response
         */
        200: TokenApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/me': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: AressApiUser | AnonymousApiUser;
      };
    };
  };
  '/users/password/forgot/captcha': {
    get: {
      req: GetUsersPasswordForgotCaptchaData;
      res: {
        /**
         * Successful Response
         */
        200: CaptchaApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/password/forgot/otp': {
    post: {
      req: PostUsersPasswordForgotOtpData;
      res: {
        /**
         * Successful Response
         */
        200: GetOtpForForgotPasswordResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/password/forgot/reset': {
    post: {
      req: PostUsersPasswordForgotResetData;
      res: {
        /**
         * Successful Response
         */
        200: ResetForgotPasswordByOtpResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/password/change/otp': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: GetOtpForChangePasswordResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/password/change': {
    post: {
      req: PostUsersProfilePasswordChangeData;
      res: {
        /**
         * Successful Response
         */
        200: ChangePasswordByOtpApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/password/validate': {
    post: {
      req: PostUsersProfilePasswordValidateData;
      res: {
        /**
         * Successful Response
         */
        200: ValidatePasswordForUserResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/phone/change/otp': {
    post: {
      req: PostUsersProfilePhoneChangeOtpData;
      res: {
        /**
         * Successful Response
         */
        200: ChangePhoneGetOtpResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/phone/change': {
    post: {
      req: PostUsersProfilePhoneChangeData;
      res: {
        /**
         * Successful Response
         */
        200: ChangePhoneByOtpResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/email/change/otp': {
    post: {
      req: PostUsersProfileEmailChangeOtpData;
      res: {
        /**
         * Successful Response
         */
        200: ChangeEmailGetOtpResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/email/change': {
    post: {
      req: PostUsersProfileEmailChangeData;
      res: {
        /**
         * Successful Response
         */
        200: ChangeEmailByOtpResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/username/change': {
    post: {
      req: PostUsersProfileUsernameChangeData;
      res: {
        /**
         * Successful Response
         */
        200: ChangeUsernameResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/profile/picture/change': {
    post: {
      req: PostUsersProfilePictureChangeData;
      res: {
        /**
         * Successful Response
         */
        200: ChangeProfilePictureResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/users/logout': {
    post: {
      res: {
        /**
         * Successful Response
         */
        200: LogoutResponseApiModel;
      };
    };
  };
  '/reports': {
    get: {
      req: GetReportsData;
      res: {
        /**
         * Successful Response
         */
        200: Array<FinancialReportListItemApiModel>;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/reports/categories': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<FinancialReportCategoryApiModel>;
      };
    };
  };
  '/reports/request': {
    post: {
      req: PostReportsRequestData;
      res: {
        /**
         * Successful Response
         */
        200: RequestReportResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/reports/{report_id}': {
    get: {
      req: GetReportsByReportIdData;
      res: {
        /**
         * Successful Response
         */
        200: FinancialReportDetailsApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    post: {
      req: PostReportsByReportIdData;
      res: {
        /**
         * Successful Response
         */
        200: FinancialReportCalculationApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/reports/{report_id}/favorite': {
    post: {
      req: PostReportsByReportIdFavoriteData;
      res: {
        /**
         * Successful Response
         */
        200: UserReportFavoriteStatus;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    delete: {
      req: DeleteReportsByReportIdFavoriteData;
      res: {
        /**
         * Successful Response
         */
        200: UserReportFavoriteStatus;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/reports/{report_id}/screenshot': {
    post: {
      req: PostReportsByReportIdScreenshotData;
      res: {
        /**
         * Successful Response
         */
        200: ReportScreenshotResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<DashboardListItemApiModel>;
      };
    };
    put: {
      req: PutDashboardsData;
      res: {
        /**
         * Successful Response
         */
        200: CreateDashboardResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}': {
    get: {
      req: GetDashboardsByDashboardIdData;
      res: {
        /**
         * Successful Response
         */
        200: DashboardDetailsApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    post: {
      req: PostDashboardsByDashboardIdData;
      res: {
        /**
         * Successful Response
         */
        200: DashboardListItemApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    delete: {
      req: DeleteDashboardsByDashboardIdData;
      res: {
        /**
         * Successful Response
         */
        200: Array<DashboardListItemApiModel>;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
    put: {
      req: PutDashboardsByDashboardIdData;
      res: {
        /**
         * Successful Response
         */
        200: DashboardItemApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}/duplicate': {
    post: {
      req: PostDashboardsByDashboardIdDuplicateData;
      res: {
        /**
         * Successful Response
         */
        200: DashboardDetailsApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}/preview': {
    get: {
      req: GetDashboardsByDashboardIdPreviewData;
      res: {
        /**
         * Successful Response
         */
        200: Array<DashboardItemPreviewApiModel>;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}/items/{dashboard_item_id}': {
    delete: {
      req: DeleteDashboardsByDashboardIdItemsByDashboardItemIdData;
      res: {
        /**
         * Successful Response
         */
        200: DeleteDashboardItemResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}/items/{dashboard_item_id}/replace': {
    post: {
      req: PostDashboardsByDashboardIdItemsByDashboardItemIdReplaceData;
      res: {
        /**
         * Successful Response
         */
        200: DashboardItemApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}/items/{dashboard_item_id}/screenshot': {
    post: {
      req: PostDashboardsByDashboardIdItemsByDashboardItemIdScreenshotData;
      res: {
        /**
         * Successful Response
         */
        200: DashboardItemScreenshotResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}/items/{dashboard_item_id}/calculations': {
    post: {
      req: PostDashboardsByDashboardIdItemsByDashboardItemIdCalculationsData;
      res: {
        /**
         * Successful Response
         */
        200: DashboardItemApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/dashboards/{dashboard_id}/items/{dashboard_item_id}/reorder': {
    post: {
      req: PostDashboardsByDashboardIdItemsByDashboardItemIdReorderData;
      res: {
        /**
         * Successful Response
         */
        200: unknown;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/funds': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: Array<FundListItemApiModel>;
      };
    };
  };
  '/funds/type/{fund_type}': {
    get: {
      req: GetFundsTypeByFundTypeData;
      res: {
        /**
         * Successful Response
         */
        200: Array<FundListItemApiModel>;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/funds/table': {
    get: {
      req: GetFundsTableData;
      res: {
        /**
         * Successful Response
         */
        200: FundTableResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/funds/table/pin': {
    post: {
      req: PostFundsTablePinData;
      res: {
        /**
         * Successful Response
         */
        200: PinFundInTableTabResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
  '/funds/table/unpin': {
    post: {
      req: PostFundsTableUnpinData;
      res: {
        /**
         * Successful Response
         */
        200: UnpinFundInTableTabResponseApiModel;
        /**
         * Validation Error
         */
        422: HTTPValidationError;
      };
    };
  };
};
