# Install dependencies only when needed
FROM node:20-alpine AS deps
WORKDIR /app

# Copy only the package.json and lock file
COPY apps/fe-app/package.json ./
COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig.base.json ./
COPY tsconfig.base.json /tsconfig.base.json
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm
COPY --from=deps /app/node_modules ./node_modules
COPY apps/fe-app ./
COPY libs ./libs
COPY shared ./shared
COPY tsconfig.base.json ./
COPY tsconfig.base.json /tsconfig.base.json
RUN pnpm build

# Production image, copy all the files and run next
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# If you use a custom server, expose the port it runs on
EXPOSE 3000

# Copy built assets from builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

CMD ["pnpm", "start"]