import {
  addFormatsToRows,
  cn,
  Column,
  renderCell,
  RowData,
  TableCellFormat,
  TableRow,
} from 'design-system';

const rawData: RowData<TableRow>[] = [
  {
    name: '1403',
    فروردین: '4',
    اردیبهشت: '11',
    خرداد: '7',
    تیر: '6',
    مرداد: null,
    شهریور: null,
    مهر: null,
    آبان: null,
    آذر: null,
    دی: null,
    بهمن: null,
    اسفند: null,
  },
  {
    name: '1402',
    فروردین: '-10',
    اردیبهشت: '5',
    خرداد: '-3',
    تیر: '12',
    مرداد: '10',
    شهریور: '12',
    مهر: '-13',
    آبان: '8',
    آذر: '-11',
    دی: '9',
    بهمن: '-10',
    اسفند: '-15',
  },
  {
    name: '1401',
    فروردین: '12',
    اردیبهشت: '-15',
    خرداد: '12',
    تیر: '-11',
    مرداد: '12',
    شهریور: '-12',
    مهر: '13',
    آبان: '-8',
    آذر: '-15',
    دی: '3',
    بهمن: '-12',
    اسفند: '-15',
  },
  {
    name: '1400',
    فروردین: '-10',
    اردیبهشت: '5',
    خرداد: '12',
    تیر: '-12',
    مرداد: '10',
    شهریور: '-11',
    مهر: '7',
    آبان: '8',
    آذر: '-5',
    دی: '6',
    بهمن: '-8',
    اسفند: '-15',
  },
  {
    name: '1399',
    فروردین: '12',
    اردیبهشت: '5',
    خرداد: '-10',
    تیر: '11',
    مرداد: '9',
    شهریور: '-10',
    مهر: '11',
    آبان: '-8',
    آذر: '-15',
    دی: '-6',
    بهمن: '-1',
    اسفند: '-15',
  },
  {
    name: '1398',
    فروردین: '3',
    اردیبهشت: '-15',
    خرداد: '11',
    تیر: '-10',
    مرداد: '12',
    شهریور: '-9',
    مهر: '13',
    آبان: '8',
    آذر: '-15',
    دی: '-9',
    بهمن: '-6',
    اسفند: '-15',
  },
  {
    name: '1397',
    فروردین: '12',
    اردیبهشت: '1',
    خرداد: '10',
    تیر: '-11',
    مرداد: '9',
    شهریور: '8',
    مهر: '10',
    آبان: '8',
    آذر: '-15',
    دی: '-15',
    بهمن: '3',
    اسفند: '-15',
  },
  {
    name: '1396',
    فروردین: '-13',
    اردیبهشت: '-9',
    خرداد: '9',
    تیر: '-8',
    مرداد: '7',
    شهریور: '10',
    مهر: '9',
    آبان: '8',
    آذر: '-15',
    دی: '2',
    بهمن: '-7',
    اسفند: '-15',
  },
  { type: 'separator' },
  {
    name: 'میانگین',
    فروردین: '10',
    اردیبهشت: '7',
    خرداد: '9',
    تیر: '-8',
    مرداد: '7',
    شهریور: '10',
    مهر: '9',
    آبان: '-8',
    آذر: '-15',
    دی: '15',
    بهمن: '6',
    اسفند: '15',
  },
  {
    name: 'انحراف معیار',
    فروردین: '10',
    اردیبهشت: '-3',
    خرداد: '9',
    تیر: '8',
    مرداد: '7',
    شهریور: '10',
    مهر: '-9',
    آبان: '-8',
    آذر: '-9',
    دی: '9',
    بهمن: '15',
    اسفند: '15',
  },
];

export const data = addFormatsToRows([], rawData);
const sharedStyle = 'h-[40px] flex items-center w-full mt-4 ml-4 rounded-sm';
export const schema: Column<TableRow>[] = [
  {
    key: 'name',
    header: 'سال',
    headerDivider: 'left',
  },
  ...[
    'فروردین',
    'اردیبهشت',
    'خرداد',
    'تیر',
    'مرداد',
    'شهریور',
    'مهر',
    'آبان',
    'آذر',
    'دی',
    'بهمن',
    'اسفند',
  ].map((month) => ({
    key: month,
    header: month,
    render: (
      value: number | null | string,
      rowIndex: number,
      colIndex: number,
      hoveredCol: number | null,
      hoveredRow: number | null,
      matchingCol: number | null,
      matchingRow: number | null,
      rowFormat?: TableCellFormat,
      valueBasedBg?: string,
    ) =>
      renderCell(
        value as string,
        rowIndex,
        colIndex,
        hoveredCol,
        hoveredRow,
        matchingCol,
        matchingRow,
        rowFormat,
        {
          precision: 0,
          signed: true,
          type: 'percent',
        },
        cn(
          sharedStyle,
          'justify-center min-w-[50px]',
          rowIndex === 10
            ? 'bg-gray-100'
            : ((hoveredCol !== null && hoveredCol !== colIndex) ||
                  (hoveredRow !== null && hoveredRow !== rowIndex)) &&
                rowIndex !== 9
              ? 'transparent'
              : valueBasedBg,
        ),
      ),
  })),
];
