import { addFormatsToRows, cn, Column, renderCell, RowData, TableCellFormat, TableRow } from "design-system";

const rawData: RowData<TableRow>[] = [
  {
    name: '1403',
    'فروردین': '4',
    'اردیبهشت': '11',
    'خرداد': '7',
    'تیر': '6',
    'مرداد': null,
    'شهریور': null,
    'مهر': null,
    'آبان': null,
    'آذر': null,
    'دی': null,
    'بهمن': null,
    'اسفند': null,
  },
  {
    name: '1402',
    'فروردین': '11',
    'اردیبهشت': '6',
    'خرداد': '-3',
    'تیر': '20',
    'مرداد': '17',
    'شهریور': '20',
    'مهر': '21',
    'آبان': '13',
    'آذر': '-28',
    'دی': null,
    'بهمن': '-10',
    'اسفند': '-19',
  },
  {
    name: '1401',
    'فروردین': '21',
    'اردیبهشت': '-24',
    'خرداد': '22',
    'تیر': '19',
    'مرداد': '20',
    'شهریور': '22',
    'مهر': '21',
    'آبان': '13',
    'آذر': '-28',
    'دی': null,
    'بهمن': '-12',
    'اسفند': '-19',
  },
  {
    name: '1400',
    'فروردین': '18',
    'اردیبهشت': '-22',
    'خرداد': '24',
    'تیر': '22',
    'مرداد': '18',
    'شهریور': '21',
    'مهر': '21',
    'آبان': '13',
    'آذر': '-28',
    'دی': null,
    'بهمن': '-8',
    'اسفند': '-19',
  },
  {
    name: '1399',
    'فروردین': '22',
    'اردیبهشت': '-25',
    'خرداد': '20',
    'تیر': '21',
    'مرداد': '19',
    'شهریور': '20',
    'مهر': '21',
    'آبان': '13',
    'آذر': '-28',
    'دی': null,
    'بهمن': '-1',
    'اسفند': '-19',
  },
  {
    name: '1398',
    'فروردین': '20',
    'اردیبهشت': '-23',
    'خرداد': '21',
    'تیر': '20',
    'مرداد': '22',
    'شهریور': '19',
    'مهر': '21',
    'آبان': '13',
    'آذر': '-28',
    'دی': null,
    'بهمن': '-6',
    'اسفند': '-19',
  },
  {
    name: '1397',
    'فروردین': '25',
    'اردیبهشت': '-21',
    'خرداد': '22',
    'تیر': '23',
    'مرداد': '20',
    'شهریور': '19',
    'مهر': '22',
    'آبان': '34',
    'آذر': '33',
    'دی': '34',
    'بهمن': '34',
    'اسفند': '34',
  },
  {
    name: '1396',
    'فروردین': '24',
    'اردیبهشت': '-26',
    'خرداد': '21',
    'تیر': '20',
    'مرداد': '19',
    'شهریور': '23',
    'مهر': '21',
    'آبان': '13',
    'آذر': '-28',
    'دی': null,
    'بهمن': '-7',
    'اسفند': '-19',
  },
  { type: 'separator' },
  {
    name: 'میانگین',
    'فروردین': '24',
    'اردیبهشت': '-26',
    'خرداد': '21',
    'تیر': '20',
    'مرداد': '19',
    'شهریور': '23',
    'مهر': '20',
    'آبان': '34',
    'آذر': '33',
    'دی': '34',
    'بهمن': '34',
    'اسفند': '34',
  },
  {
    name: 'انحراف معیار',
    'فروردین': '24',
    'اردیبهشت': '-26',
    'خرداد': '21',
    'تیر': '20',
    'مرداد': '19',
    'شهریور': '23',
    'مهر': '20',
    'آبان': '34',
    'آذر': '33',
    'دی': '34',
    'بهمن': '34',
    'اسفند': '34',
  },
  
  ];
  
  export const data = addFormatsToRows(
    []
  ,
    rawData
  );
  const sharedStyle =
  'h-[40px] flex items-center min-w-[78px] w-full mt-4 ml-4 rounded-sm';
  export const schema: Column<TableRow>[] = [
    {
      key: 'name',
      header: 'سال',
      headerDivider: 'left',
    },
    ...['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'].map((month) => ({
      key: month,
      header: month,
      render: (value: number | null|string, rowIndex:number, colIndex:number,     hoveredCol: number|null,
        hoveredRow: number|null,
        matchingCol: number|null,
        matchingRow: number|null,rowFormat?:TableCellFormat,valueBasedBg?:string) =>
        renderCell(
          value as string,
          rowIndex,
          colIndex,
          hoveredCol,
          hoveredRow,
          matchingCol,
          matchingRow,
          rowFormat,
          {
            precision: 0,
            signed: true,
            type: 'percent',
          },
          cn('min-w-[78px]',
            'justify-center',
            [4,5].includes(rowIndex)  && 'text-gray-1000'
          ,sharedStyle),(rowIndex === 10 ? 'bg-gray-100' : 
            (hoveredCol !== null && hoveredCol !== colIndex || hoveredRow !== null && hoveredRow !== rowIndex) && rowIndex !== 9 ? 'transparent' : valueBasedBg),

        ),
    })),
    
  ];