import dynamicIconImports from 'lucide-react/dynamicIconImports';

// custom icon valid name
export type CustomIconName =
  | 'CustomCalendar'
  | 'CustomBag'
  | 'CustomBadge'
  | 'CustomBeta'
  | 'CustomCircleSlice'
  | 'CustomWallet'
  | 'CustomScalesOfJustice'
  | 'CustomClock'
  | 'CustomCircularUser'
  | 'CustomCirlcleX'
  | 'CustomAlpha'
  | 'CustomPinLinear'
  | 'CustomPlayLinear'
  | 'CustomPinOffLinear'
  | 'CustomPinOffFill'
  | 'CustomPin'
  | 'CustomPlayFill'
  | 'CustomPinFill'
  | 'CustomBookmark'
  | 'CustomArrow'
  | 'CustomTelegram'
  | 'CustomGold'
  | 'CustomDay'
  | 'CustomEghtesadNovin'
  | 'CustomGardeshgari'
  | 'CustomGharzolhasaneMehrIran'
  | 'CustomHakmatIranian'
  | 'CustomIranzamin'
  | 'CustomKeshavarzi'
  | 'CustomKhavarmianeh'
  | 'CustomMaskan'
  | 'CustomMehrEghtesad'
  | 'CustomMellat'
  | 'CustomMelliIran'
  | 'CustomParsian'
  | 'CustomPasargad'
  | 'CustomPostBankIran'
  | 'CustomRefah'
  | 'CustomSaderat'
  | 'CustomSaman'
  | 'CustomSanatMadn'
  | 'CustomSarmayeh'
  | 'CustomSepah'
  | 'CustomShahr'
  | 'CustomSina'
  | 'CustomTejarat'
  | 'CustomAyandeh'
  | 'CustomCaretUp'
  | 'CustomCaretDown'
  | 'CustomPng'
  | 'CustomPdfLite'
  | 'CustomCsvFile'
  | 'CustomFirefox'
  | 'CustomSafari'
  | 'CustomEdge'
  | 'CustomToseeTaavon'
  | 'CustomPdf';

// this is a type of all valid icon names from lucide
export type IconName = keyof typeof dynamicIconImports | CustomIconName;

// valid icon size you can pass to IconComponent
export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'lg_plus' | 'xl';
