import './global.css';
import ReactQueryProvider from './providers/ReactQueryProvider';

export const metadata = {
  title: 'Welcome to apps/fe-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-surface-neutral-background min-w-[768px]">
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}