import { Toaster } from 'react-hot-toast';
import './global.css';
import ReactQueryProvider from './providers/ReactQueryProvider';

export const metadata = {
  title: 'Welcome to apps/fe-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Toaster
          position="bottom-center"
          containerStyle={{
            bottom: 70,
          }}
        />
      </body>
    </html>
  );
}
