import './global.css';
import { cn, Header } from 'design-system';

export const metadata = {
  title: 'Welcome to apps/fe-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'sdfsdf',
          'dfsdfs pb-10 relative m-10 pr-10 shadow-sm text-center'
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
